/**
 * Stage 4 Session 3: coarse + fine ISO mesh merge.
 *
 * The render-worker orchestrator runs the ISO pipeline twice when adaptive refinement
 * is in play: once at the user's voxel over the full scene bounds (the "coarse" mesh)
 * and once at a finer voxel within the high-residual AABB the octree identified (the
 * "fine" mesh). This module CPU-side merges them by:
 *
 *   1. Dropping coarse triangles whose centroid lies inside the fine AABB. (Centroid is
 *      a robust criterion: a triangle that straddles the AABB face is either fully
 *      inside if its centroid is inside, or kept if outside — both choices avoid
 *      visible double-counting.)
 *   2. Appending all fine triangles after the surviving coarse triangles, with the
 *      fine vertex indices offset by the surviving coarse vertex count.
 *   3. Compacting unreferenced coarse vertices (the dropped triangles' exclusively-owned
 *      vertices) so the final vertex array contains no orphans.
 *
 * Known limitation (Session 3 v1): the coarse and fine meshes do NOT share boundary
 * vertex positions — they were generated by different uniform grids — so visible cracks
 * appear at the AABB boundary where the surface enters the refinement region. Session 4
 * will replace this with paper-faithful T-junction-aware multi-resolution Marching
 * Tetrahedra in Pass 6, which generates a single watertight mesh directly.
 *
 * Re-welding by quantized position (as `weldIsoMeshByQuantizedPosition` does within a
 * single ISO export) does NOT close the cracks here because the coarse and fine
 * iso-crossings on the same SDF live at different positions per linear-interpolation —
 * the weld tolerance would have to be much larger than the fine voxel to merge them,
 * which would then over-weld within the fine mesh itself. Skipped.
 */

import type { MeshData } from "./export.mjs"
import { SIZEOF_VERTEX } from "./mdc.mjs"
import { log as dbgLog } from "../logging/debug-log.mjs"

const VERTEX_STRIDE_F32 = SIZEOF_VERTEX / Float32Array.BYTES_PER_ELEMENT

export interface AABB3 {
    min: [number, number, number]
    max: [number, number, number]
}

/**
 * Merge two ISO meshes: drop coarse triangles whose centroid is inside `fineAABB`,
 * then append all fine triangles. Returns a new `MeshData` (does not mutate inputs).
 */
export function mergeIsoMeshes(coarse: MeshData, fine: MeshData, fineAABB: AABB3): MeshData {
    const coarseTris = coarse.tris
    const coarseVerts = coarse.verts
    const fineTris = fine.tris
    const fineVerts = fine.verts

    const coarseTriCount = (coarseTris.length / 3) | 0
    const coarseVertCount = (coarseVerts.length / VERTEX_STRIDE_F32) | 0

    // First pass: classify coarse triangles. `keep[t]` is true if its centroid is OUTSIDE
    // the fine AABB. We compute the centroid in-line via 3 vertex lookups.
    const keep = new Uint8Array(coarseTriCount)
    let keptCount = 0
    const used = new Uint8Array(coarseVertCount)
    const minX = fineAABB.min[0], minY = fineAABB.min[1], minZ = fineAABB.min[2]
    const maxX = fineAABB.max[0], maxY = fineAABB.max[1], maxZ = fineAABB.max[2]

    for (let t = 0; t < coarseTriCount; t++) {
        const i0 = coarseTris[t * 3]!
        const i1 = coarseTris[t * 3 + 1]!
        const i2 = coarseTris[t * 3 + 2]!
        const o0 = i0 * VERTEX_STRIDE_F32
        const o1 = i1 * VERTEX_STRIDE_F32
        const o2 = i2 * VERTEX_STRIDE_F32
        const cx = (coarseVerts[o0]! + coarseVerts[o1]! + coarseVerts[o2]!) / 3
        const cy = (coarseVerts[o0 + 1]! + coarseVerts[o1 + 1]! + coarseVerts[o2 + 1]!) / 3
        const cz = (coarseVerts[o0 + 2]! + coarseVerts[o1 + 2]! + coarseVerts[o2 + 2]!) / 3
        const inside = cx >= minX && cx <= maxX && cy >= minY && cy <= maxY && cz >= minZ && cz <= maxZ
        if (!inside) {
            keep[t] = 1
            keptCount++
            // Mark these coarse vertices as referenced so we keep them.
            used[i0] = 1
            used[i1] = 1
            used[i2] = 1
        }
    }

    // Second pass: build the dense remap for surviving coarse vertices.
    const coarseRemap = new Uint32Array(coarseVertCount)
    let outCoarseVertCount = 0
    for (let v = 0; v < coarseVertCount; v++) {
        if (used[v]) {
            coarseRemap[v] = outCoarseVertCount
            outCoarseVertCount++
        }
    }

    // Compose the merged vertex array: surviving coarse + all fine.
    const fineVertCount = (fineVerts.length / VERTEX_STRIDE_F32) | 0
    const totalVertCount = outCoarseVertCount + fineVertCount
    const mergedVerts = new Float32Array(totalVertCount * VERTEX_STRIDE_F32)
    // Copy surviving coarse vertices.
    for (let v = 0; v < coarseVertCount; v++) {
        if (!used[v]) continue
        const src = v * VERTEX_STRIDE_F32
        const dst = coarseRemap[v]! * VERTEX_STRIDE_F32
        for (let k = 0; k < VERTEX_STRIDE_F32; k++) {
            mergedVerts[dst + k] = coarseVerts[src + k]!
        }
    }
    // Copy all fine vertices straight after.
    mergedVerts.set(fineVerts, outCoarseVertCount * VERTEX_STRIDE_F32)

    // Compose the merged triangle index array: surviving coarse (remapped) + all fine
    // (offset by surviving coarse vertex count).
    const fineTriCount = (fineTris.length / 3) | 0
    const totalTriCount = keptCount + fineTriCount
    const mergedTris = new Uint32Array(totalTriCount * 3)
    let writeTri = 0
    for (let t = 0; t < coarseTriCount; t++) {
        if (!keep[t]) continue
        mergedTris[writeTri * 3] = coarseRemap[coarseTris[t * 3]!]!
        mergedTris[writeTri * 3 + 1] = coarseRemap[coarseTris[t * 3 + 1]!]!
        mergedTris[writeTri * 3 + 2] = coarseRemap[coarseTris[t * 3 + 2]!]!
        writeTri++
    }
    const fineIndexOffset = outCoarseVertCount
    for (let t = 0; t < fineTriCount; t++) {
        mergedTris[writeTri * 3] = fineTris[t * 3]! + fineIndexOffset
        mergedTris[writeTri * 3 + 1] = fineTris[t * 3 + 1]! + fineIndexOffset
        mergedTris[writeTri * 3 + 2] = fineTris[t * 3 + 2]! + fineIndexOffset
        writeTri++
    }

    dbgLog("IsoExport").info(
        `Stage 4 S3 merge: coarse ${coarseTriCount} → ${keptCount} tris (dropped ${coarseTriCount - keptCount} `
        + `inside fine AABB), + fine ${fineTriCount} = ${totalTriCount} total. `
        + `verts: ${coarseVertCount} → ${outCoarseVertCount} surviving + ${fineVertCount} fine = ${totalVertCount}.`,
    )
    return { verts: mergedVerts, tris: mergedTris }
}

/**
 * Pad the fine AABB by `padMm` on each side. Used when scheduling the secondary fine
 * pass so the fine mesh extends slightly past the actual feature region — gives the
 * coarse-triangle drop step a small overlap zone where it can pick the coarse triangle
 * over the fine one (or vice versa). For Session 3 v1 this doesn't close cracks but
 * ensures we don't accidentally drop coarse triangles we have no fine replacement for.
 */
export function padAABB(aabb: AABB3, padMm: number): AABB3 {
    return {
        min: [aabb.min[0] - padMm, aabb.min[1] - padMm, aabb.min[2] - padMm],
        max: [aabb.max[0] + padMm, aabb.max[1] + padMm, aabb.max[2] + padMm],
    }
}
