/**
 * Stage 4 (Manson & Schaefer §5.1) — adaptive octree foundation.
 *
 * Session 1 (current file): CPU-side octree representation built from the per-cube QEF
 * residual readback after `placeCubeDuals_Pass5`. The octree's leaves identify which
 * uniform-grid cubes the paper would subdivide for finer dual placement. Statistics are
 * logged for verification but the mesh output is unchanged in this session — multi-
 * resolution Marching Tetrahedra (Session 2+) will consume the leaf list.
 *
 * Why CPU for now: the per-level subdivision loop needs at minimum a per-level readback
 * to know how many leaves remain (so the dispatch-on-marked-leaves child allocator
 * doesn't dispatch over an empty set). For a small initial set of "subdivide candidates"
 * the readback overhead dominates GPU runtime anyway, so doing the bookkeeping CPU-side
 * is the cleanest first cut. Sessions 2+ will move the per-level loop to the GPU once
 * the multi-resolution dual-placement passes are in place.
 *
 * Octree node layout (one per leaf — interior nodes are not retained):
 *   - cellPos: vec3u — base-grid cube position at this leaf's depth (each level halves
 *     the voxel size, so a depth-2 leaf has cellPos in [0, 4×nx) × ...)
 *   - depth: number — 0 = base uniform grid; 1 = first refinement; 2 = second; ...
 *   - parentResidual: number — the QEF residual that triggered subdivision (informative).
 *
 * The leaf list is the union of:
 *   1. Base-grid cubes that were below the residual threshold (no subdivision needed)
 *   2. All sub-cubes generated by recursive subdivision of high-residual ancestors,
 *      down to the leaves at min(maxDepth, refinement-stops-when-no-more-marks).
 */

import { log as dbgLog } from "../logging/debug-log.mjs"

/** A leaf cube in the adaptive octree. Coordinates are at depth-resolution (each
 *  refinement level halves the voxel size, so cellPos / 2^depth gives base coords). */
export interface OctreeLeaf {
    /** Cube min-corner position at this leaf's depth resolution.
     *  At depth `d`, cellPos.x is in `[0, nx_base * 2^d)`. */
    cellPos: [number, number, number]
    /** 0 = base uniform grid; positive = refinement levels below base. */
    depth: number
    /** QEF residual at the dual position of the COVERING base cube. Useful for
     *  visualising which leaves came from refinement vs. were "good enough" at base. */
    coveringResidual: number
}

export interface OctreeBuildResult {
    /** All leaves in the adaptive octree (mix of base + refined depths). */
    leaves: OctreeLeaf[]
    /** Total leaf count per depth bucket (depth → count). */
    leavesPerDepth: Map<number, number>
    /** How many base-grid cubes were marked for subdivision at any level. */
    baseCubesRefined: number
    /** Total residual sum (CPU-side stat for relative cross-mesh comparison). */
    totalResidual: number
    /** Maximum residual observed (helps users tune `octreeResidualThreshold`). */
    maxResidual: number
    /** Number of leaves the equivalent UNIFORM grid at maxDepth would have produced
     *  (= base cube count × 8^maxDepth). Used to compute adaptivity ratio in logs. */
    equivalentUniformLeafCount: number
    /** Adaptivity ratio = leaves.length / equivalentUniformLeafCount. <1 = octree saves
     *  cells; closer to 1 = uniform-equivalent (refinement was widespread). */
    adaptivityRatio: number
    /** Per-step CPU timing (ms). */
    timingMs: Record<string, number>
}

/**
 * Build the adaptive octree from per-cube QEF residuals (session 1: CPU-only).
 *
 * Algorithm (paper §5.1, top-down):
 *   1. Start with the base uniform grid as level-0 leaves.
 *   2. For each level L (0 ≤ L < maxDepth):
 *      a. For each leaf at depth L, mark for subdivision iff
 *         coveringResidual > threshold AND depth < maxDepth.
 *      b. Each marked leaf produces 8 children at depth L+1 (Morton octant offsets).
 *      c. Children inherit the parent's residual as `coveringResidual` for their next
 *         subdivision check (in this CPU-only session — Session 2 will compute fresh
 *         per-child residuals on the GPU after sub-cube dual placement).
 *   3. Stop when no leaves are marked or all leaves hit maxDepth.
 *
 * Note on "covering residual" inheritance: a true paper implementation would re-compute
 * the QEF residual at each new sub-cube level (which requires GPU sub-cube dual
 * placement, deferred to Session 2). In Session 1 we use the parent's residual as a
 * conservative upper bound for the children — if parent says "subdivide", all 8
 * children also "want to subdivide" all the way down. This means Session 1's leaf set
 * is a strict superset of what the full algorithm would produce; Session 2 will prune
 * via per-child residuals.
 */
export function buildOctreeFromCubeResiduals(
    activeCubeCellPositions: Uint32Array, // packed [x0, y0, z0, x1, y1, z1, ...]
    cubeResiduals: Float32Array,           // one f32 per active cube (matches Pass 5 local_slot)
    nxBase: number,
    nyBase: number,
    nzBase: number,
    threshold: number,
    maxDepth: number,
): OctreeBuildResult {
    const t0 = performance.now()
    const cubeCount = (activeCubeCellPositions.length / 3) | 0
    if (cubeResiduals.length < cubeCount) {
        throw new Error(
            `iso-octree: cubeResiduals length (${cubeResiduals.length}) is less than `
            + `active cube count (${cubeCount}); upstream Pass 5 buffer mismatch?`,
        )
    }

    // Initial leaves at depth 0 — every active cube becomes a leaf with its own residual.
    // We retain inactive cubes implicitly: they're absent from `activeCubeCellPositions`
    // and contribute neither to the octree nor (by definition) to the iso surface.
    let currentLeaves: OctreeLeaf[] = new Array(cubeCount)
    let totalResidual = 0
    let maxResidual = 0
    for (let i = 0; i < cubeCount; i++) {
        const r = cubeResiduals[i]!
        const safeR = Number.isFinite(r) ? Math.max(0, r) : 0
        totalResidual += safeR
        if (safeR > maxResidual) maxResidual = safeR
        currentLeaves[i] = {
            cellPos: [
                activeCubeCellPositions[i * 3]!,
                activeCubeCellPositions[i * 3 + 1]!,
                activeCubeCellPositions[i * 3 + 2]!,
            ],
            depth: 0,
            coveringResidual: safeR,
        }
    }
    const tLeavesAlloced = performance.now()

    // Level-by-level subdivision. A "marked" leaf splits into 8 children at depth+1.
    // The 8 children's cellPos = parent.cellPos * 2 + (octant offset 0..7 → (i&1, (i>>1)&1, (i>>2)&1)).
    let baseCubesRefined = 0
    const refinedBaseSet = new Set<number>() // pack (x, y, z) into a single key
    const packBaseKey = (x: number, y: number, z: number) =>
        (x | 0) + (y | 0) * nxBase + (z | 0) * (nxBase * nyBase)

    for (let level = 0; level < maxDepth; level++) {
        const nextLeaves: OctreeLeaf[] = []
        let levelMarks = 0

        for (const leaf of currentLeaves) {
            // Marked iff residual exceeds threshold AND we haven't bottomed out.
            // The threshold scaling stays constant across depths in this Session 1 — the
            // paper notes this matches their "function-error" criterion which is depth-
            // independent (a flat region stays flat at any sub-resolution). Session 2's
            // per-child residual recompute will let us drop the constant-threshold
            // assumption; for now it's a safe conservative choice.
            if (leaf.depth >= maxDepth || leaf.coveringResidual <= threshold) {
                nextLeaves.push(leaf)
                continue
            }
            levelMarks++

            // Track which base-grid cubes contributed to refinement (for stats).
            const baseScale = 1 << leaf.depth
            const baseX = (leaf.cellPos[0] / baseScale) | 0
            const baseY = (leaf.cellPos[1] / baseScale) | 0
            const baseZ = (leaf.cellPos[2] / baseScale) | 0
            const baseKey = packBaseKey(baseX, baseY, baseZ)
            if (!refinedBaseSet.has(baseKey)) {
                refinedBaseSet.add(baseKey)
                baseCubesRefined++
            }

            // Emit 8 children. Each child's cellPos at depth+1 = parent*2 + octant.
            const px = leaf.cellPos[0] * 2
            const py = leaf.cellPos[1] * 2
            const pz = leaf.cellPos[2] * 2
            for (let oct = 0; oct < 8; oct++) {
                nextLeaves.push({
                    cellPos: [
                        px + (oct & 1),
                        py + ((oct >> 1) & 1),
                        pz + ((oct >> 2) & 1),
                    ],
                    depth: leaf.depth + 1,
                    coveringResidual: leaf.coveringResidual, // see Session-1 inheritance note above
                })
            }
        }

        currentLeaves = nextLeaves
        if (levelMarks === 0) {
            // No more refinement; we're done.
            break
        }
    }
    const tRefined = performance.now()

    // Per-depth leaf histogram for logs.
    const leavesPerDepth = new Map<number, number>()
    for (const leaf of currentLeaves) {
        leavesPerDepth.set(leaf.depth, (leavesPerDepth.get(leaf.depth) ?? 0) + 1)
    }

    // Adaptivity ratio: how many leaves we have vs. what a uniform grid at maxDepth would
    // have generated. <1 = octree saves cells; 1 = no savings (refinement was universal).
    const equivalentUniformLeafCount = cubeCount * Math.pow(8, maxDepth)
    const adaptivityRatio = equivalentUniformLeafCount > 0
        ? currentLeaves.length / equivalentUniformLeafCount
        : 1

    const result: OctreeBuildResult = {
        leaves: currentLeaves,
        leavesPerDepth,
        baseCubesRefined,
        totalResidual,
        maxResidual,
        equivalentUniformLeafCount,
        adaptivityRatio,
        timingMs: {
            initialLeaves: Math.round((tLeavesAlloced - t0) * 100) / 100,
            refine: Math.round((tRefined - tLeavesAlloced) * 100) / 100,
            total: Math.round((tRefined - t0) * 100) / 100,
        },
    }
    return result
}

/**
 * Auto-tune the residual threshold so a target percentile of cubes are flagged for
 * subdivision. Useful when the user doesn't have a feel for what residual values to
 * expect (they depend on `voxelSize` and SDF magnitude).
 *
 * `targetRefinedFraction` of 0.05 = "flag the top 5% most-curved cubes for subdivision".
 */
export function pickResidualThresholdFromPercentile(
    residuals: Float32Array,
    targetRefinedFraction: number,
): number {
    const safeFraction = Math.max(0, Math.min(1, targetRefinedFraction))
    if (residuals.length === 0 || safeFraction === 0) return Infinity

    // Copy + sort ascending. For very large arrays this is O(N log N); CPU-side stage 1
    // is fine, will move to a GPU radix-sort if it ever becomes a bottleneck.
    const sorted = new Float32Array(residuals)
    sorted.sort()
    const idx = Math.floor((1 - safeFraction) * sorted.length)
    return sorted[Math.min(idx, sorted.length - 1)] ?? Infinity
}

/**
 * Format the octree build result as a single human-readable line for `dbgLog` output.
 * Includes leaf totals, per-depth distribution, residual range, and adaptivity ratio.
 */
export function formatOctreeStats(result: OctreeBuildResult): string {
    const perDepth = Array.from(result.leavesPerDepth.entries())
        .sort((a, b) => a[0] - b[0])
        .map(([d, n]) => `d${d}=${n}`)
        .join(",")
    const ratioPct = (result.adaptivityRatio * 100).toFixed(2)
    const t = result.timingMs
    return `octree: leaves=${result.leaves.length} (${perDepth}), refined=${result.baseCubesRefined} base cubes, `
        + `residual sum=${result.totalResidual.toExponential(3)} max=${result.maxResidual.toExponential(3)}, `
        + `adaptivity=${ratioPct}% of uniform@maxDepth, CPU ${t.total} ms`
}

/** Convenience: log the octree statistics under the IsoExport debug module. */
export function logOctreeStats(result: OctreeBuildResult): void {
    dbgLog("IsoExport").debug(formatOctreeStats(result))
}

// ============================== Stage 4 Session 2 ==============================
// GPU sub-cube dual placement support.
//
// The CPU octree builder above produces leaves at multiple depths. Session 2 takes
// the depth-1 leaves and dispatches a GPU pass (`placeChildCubeDuals_Pass11`) that
// computes a 4D-QEF cube dual for each child sub-cube. Session 2 ONLY supports
// 1-level subdivision (depth = 1, octant 0..7); deeper levels are Session 3+ and
// require a different descriptor format + multi-level Marching Tetrahedra in Pass 6.

/** A single child sub-cube descriptor matching the WGSL `childCubeInfo[i]` vec4u layout. */
export interface ChildCubeInfo {
    /** Parent's base-grid position (depth-0 cube coords, in [0, nx) × ...). */
    parentX: number
    parentY: number
    parentZ: number
    /** Octant within parent: bit 0 = x, bit 1 = y, bit 2 = z. Range 0..7. */
    octant: number
}

/**
 * Walk the octree leaves and emit one `ChildCubeInfo` per depth-1 leaf.
 *
 * Session 2 limitation: drops leaves at depth ≥ 2 (logged for diagnostics). A leaf at
 * depth 2 has cellPos at quarter-voxel resolution; encoding its octant chain requires
 * either a packed Morton path or per-leaf depth field, which the current vec4u
 * descriptor doesn't support. Session 3 will widen the descriptor.
 *
 * Returns the child list AND the count of skipped deeper-than-1 leaves so the
 * orchestrator can log "X depth-2+ leaves not yet supported by Pass 11".
 */
export function buildChildCubeListFromOctree(octree: OctreeBuildResult): {
    children: ChildCubeInfo[]
    skippedDeeperLeaves: number
} {
    const children: ChildCubeInfo[] = []
    let skippedDeeperLeaves = 0

    for (const leaf of octree.leaves) {
        if (leaf.depth === 0) continue
        if (leaf.depth > 1) {
            skippedDeeperLeaves++
            continue
        }
        // Depth = 1 → cellPos is at half-voxel coords. Parent at (cellPos >> 1) and
        // octant at (cellPos & 1) packed across axes.
        const cx = leaf.cellPos[0]
        const cy = leaf.cellPos[1]
        const cz = leaf.cellPos[2]
        children.push({
            parentX: cx >> 1,
            parentY: cy >> 1,
            parentZ: cz >> 1,
            octant: (cx & 1) | ((cy & 1) << 1) | ((cz & 1) << 2),
        })
    }

    return { children, skippedDeeperLeaves }
}

/** Stride in u32 of one packed `ChildCubeInfo` entry — must match `vec4u` layout. */
export const CHILD_CUBE_INFO_STRIDE_U32 = 4

/** Pack the child-cube list into a Uint32Array for GPU upload (vec4u per entry). */
export function packChildCubeInfo(children: ChildCubeInfo[]): Uint32Array {
    const packed = new Uint32Array(children.length * CHILD_CUBE_INFO_STRIDE_U32)
    for (let i = 0; i < children.length; i++) {
        const c = children[i]!
        packed[i * CHILD_CUBE_INFO_STRIDE_U32] = c.parentX >>> 0
        packed[i * CHILD_CUBE_INFO_STRIDE_U32 + 1] = c.parentY >>> 0
        packed[i * CHILD_CUBE_INFO_STRIDE_U32 + 2] = c.parentZ >>> 0
        packed[i * CHILD_CUBE_INFO_STRIDE_U32 + 3] = c.octant >>> 0
    }
    return packed
}

/**
 * Compute summary statistics about an array of QEF residuals (parent or child).
 * Useful for "did refinement help?" comparisons in the diagnostic log: if the
 * child residual distribution is significantly LOWER than the parent residuals
 * for the same cubes, the refinement is mathematically working — each sub-cube
 * fits the local SDF tangent planes better than the parent did.
 */
export function summarizeResidualDistribution(residuals: Float32Array | number[]): {
    count: number
    sum: number
    max: number
    mean: number
    /** P50 of finite, non-negative residuals. */
    median: number
    /** P95 of finite, non-negative residuals. */
    p95: number
} {
    let count = 0
    let sum = 0
    let max = 0
    const sorted: number[] = []
    for (let i = 0; i < residuals.length; i++) {
        const v = residuals[i]!
        if (!Number.isFinite(v) || v < 0) continue
        count++
        sum += v
        if (v > max) max = v
        sorted.push(v)
    }
    sorted.sort((a, b) => a - b)
    const median = count > 0 ? (sorted[Math.floor(count * 0.5)] ?? 0) : 0
    const p95 = count > 0 ? (sorted[Math.floor(count * 0.95)] ?? 0) : 0
    const mean = count > 0 ? sum / count : 0
    return { count, sum, max, mean, median, p95 }
}
