/**
 * Stage 4 (Manson & Schaefer §5.1) — adaptive octree foundation.
 *
 * Session 1 (current file): CPU-side octree representation built from the per-cube QEF
 * residual readback after `placeCubeDuals_Pass5`. The octree's leaves identify which
 * uniform-grid cubes the paper would subdivide for finer dual placement. Statistics are
 * logged for verification but the mesh output is unchanged in this session — multi-
 * resolution Marching Tetrahedra (Session 2+) will consume the leaf list.
 *
 * Why CPU for now: the per-level subdivision loop needs at minimum a per-level readback
 * to know how many leaves remain (so the dispatch-on-marked-leaves child allocator
 * doesn't dispatch over an empty set). For a small initial set of "subdivide candidates"
 * the readback overhead dominates GPU runtime anyway, so doing the bookkeeping CPU-side
 * is the cleanest first cut. Sessions 2+ will move the per-level loop to the GPU once
 * the multi-resolution dual-placement passes are in place.
 *
 * Octree node layout (one per leaf — interior nodes are not retained):
 *   - cellPos: vec3u — base-grid cube position at this leaf's depth (each level halves
 *     the voxel size, so a depth-2 leaf has cellPos in [0, 4×nx) × ...)
 *   - depth: number — 0 = base uniform grid; 1 = first refinement; 2 = second; ...
 *   - parentResidual: number — the QEF residual that triggered subdivision (informative).
 *
 * The leaf list is the union of:
 *   1. Base-grid cubes that were below the residual threshold (no subdivision needed)
 *   2. All sub-cubes generated by recursive subdivision of high-residual ancestors,
 *      down to the leaves at min(maxDepth, refinement-stops-when-no-more-marks).
 */

import { log as dbgLog } from "../logging/debug-log.mjs"
import { encodeSparseDualHashKeyBigInt, SPARSE_HASH_KNUTH, SPARSE_HASH_KNUTH_HI } from "./iso-sparse.mjs"

/** Maximum `octreeMaxDepth` (subdivision levels past the base grid) supported by the GPU path. */
export const ISO_OCTREE_MAX_DEPTH = 5

/** Sparse-hash linear payload: 32 low bits + 28 high bits in `key_hi` (with cell type). */
export const SPARSE_HASH_LINEAR_INDEX_BITS = 60
export const SPARSE_HASH_LINEAR_INDEX_MAX = (1n << 60n) - 1n

export function clampOctreeMaxDepth(d: number | undefined, fallback = 2): number {
    const n = Math.floor(d ?? fallback)
    if (!Number.isFinite(n)) return fallback
    return Math.min(ISO_OCTREE_MAX_DEPTH, Math.max(1, n))
}

export function subAxisMulFromMaxDepth(maxDepth: number): number {
    return 1 << maxDepth
}

/** Throws if any sub-grid linear index used in sparse keys could exceed the 60-bit wire format. */
export function assertFineSubGridHashPayloadFits(nxBase: number, nyBase: number, nzBase: number, subMul: number): void {
    const snx = subMul * nxBase
    const sny = subMul * nyBase
    const snz = subMul * nzBase
    const candidates = [
        subCubeLinearIdxBig(snx - 1, sny - 1, snz - 1, nxBase, nyBase, subMul),
        subEdgeXLinearIdxBig(snx - 1, sny, snz, nxBase, nyBase, subMul),
        subEdgeYLinearIdxBig(snx, sny - 1, snz, nxBase, nyBase, subMul),
        subEdgeZLinearIdxBig(snx, sny, snz - 1, nxBase, nyBase, subMul),
        subFaceYZLinearIdxBig(snx, sny - 1, snz - 1, nxBase, nyBase, subMul),
        subFaceXZLinearIdxBig(snx - 1, sny, snz - 1, nxBase, nyBase, subMul),
        subFaceXYLinearIdxBig(snx - 1, sny - 1, snz, nxBase, nyBase, subMul),
    ]
    let maxLin = 0n
    for (const c of candidates) {
        if (c > maxLin) maxLin = c
    }
    if (maxLin > SPARSE_HASH_LINEAR_INDEX_MAX) {
        throw new Error(
            `ISO adaptive octree: finest sub-grid linear index exceeds ${SPARSE_HASH_LINEAR_INDEX_BITS}-bit `
            + `hash payload (nx=${nxBase}, ny=${nyBase}, nz=${nzBase}, subMul=${subMul}). Coarsen voxel or reduce octreeMaxDepth.`,
        )
    }
}

/** A leaf cube in the adaptive octree. Coordinates are at depth-resolution (each
 *  refinement level halves the voxel size, so cellPos / 2^depth gives base coords). */
export interface OctreeLeaf {
    /** Cube min-corner position at this leaf's depth resolution.
     *  At depth `d`, cellPos.x is in `[0, nx_base * 2^d)`. */
    cellPos: [number, number, number]
    /** 0 = base uniform grid; positive = refinement levels below base. */
    depth: number
    /** QEF residual at the dual position of the COVERING base cube. Useful for
     *  visualising which leaves came from refinement vs. were "good enough" at base. */
    coveringResidual: number
}

export interface OctreeBuildResult {
    /** All leaves in the adaptive octree (mix of base + refined depths). */
    leaves: OctreeLeaf[]
    /** Total leaf count per depth bucket (depth → count). */
    leavesPerDepth: Map<number, number>
    /** How many base-grid cubes were marked for subdivision at any level. */
    baseCubesRefined: number
    /** Total residual sum (CPU-side stat for relative cross-mesh comparison). */
    totalResidual: number
    /** Maximum residual observed (helps users tune `octreeResidualThreshold`). */
    maxResidual: number
    /** Number of leaves the equivalent UNIFORM grid at maxDepth would have produced
     *  (= base cube count × 8^maxDepth). Used to compute adaptivity ratio in logs. */
    equivalentUniformLeafCount: number
    /** Adaptivity ratio = leaves.length / equivalentUniformLeafCount. <1 = octree saves
     *  cells; closer to 1 = uniform-equivalent (refinement was widespread). */
    adaptivityRatio: number
    /** Per-step CPU timing (ms). */
    timingMs: Record<string, number>
}

/**
 * Build the adaptive octree from per-cube QEF residuals (session 1: CPU-only).
 *
 * Algorithm (paper §5.1, top-down):
 *   1. Start with the base uniform grid as level-0 leaves.
 *   2. For each level L (0 ≤ L < maxDepth):
 *      a. For each leaf at depth L, mark for subdivision iff
 *         coveringResidual > threshold AND depth < maxDepth.
 *      b. Each marked leaf produces 8 children at depth L+1 (Morton octant offsets).
 *      c. Children inherit the parent's residual as `coveringResidual` for their next
 *         subdivision check (in this CPU-only session — Session 2 will compute fresh
 *         per-child residuals on the GPU after sub-cube dual placement).
 *   3. Stop when no leaves are marked or all leaves hit maxDepth.
 *
 * Note on "covering residual" inheritance: a true paper implementation would re-compute
 * the QEF residual at each new sub-cube level (which requires GPU sub-cube dual
 * placement, deferred to Session 2). In Session 1 we use the parent's residual as a
 * conservative upper bound for the children — if parent says "subdivide", all 8
 * children also "want to subdivide" all the way down. This means Session 1's leaf set
 * is a strict superset of what the full algorithm would produce; Session 2 will prune
 * via per-child residuals.
 */
export function buildOctreeFromCubeResiduals(
    activeCubeCellPositions: Uint32Array, // packed [x0, y0, z0, x1, y1, z1, ...]
    cubeResiduals: Float32Array,           // one f32 per active cube (matches Pass 5 local_slot)
    nxBase: number,
    nyBase: number,
    nzBase: number,
    threshold: number,
    maxDepth: number,
): OctreeBuildResult {
    const t0 = performance.now()
    const cubeCount = (activeCubeCellPositions.length / 3) | 0
    if (cubeResiduals.length < cubeCount) {
        throw new Error(
            `iso-octree: cubeResiduals length (${cubeResiduals.length}) is less than `
            + `active cube count (${cubeCount}); upstream Pass 5 buffer mismatch?`,
        )
    }

    // Initial leaves at depth 0 — every active cube becomes a leaf with its own residual.
    // We retain inactive cubes implicitly: they're absent from `activeCubeCellPositions`
    // and contribute neither to the octree nor (by definition) to the iso surface.
    let currentLeaves: OctreeLeaf[] = new Array(cubeCount)
    let totalResidual = 0
    let maxResidual = 0
    for (let i = 0; i < cubeCount; i++) {
        const r = cubeResiduals[i]!
        const safeR = Number.isFinite(r) ? Math.max(0, r) : 0
        totalResidual += safeR
        if (safeR > maxResidual) maxResidual = safeR
        currentLeaves[i] = {
            cellPos: [
                activeCubeCellPositions[i * 3]!,
                activeCubeCellPositions[i * 3 + 1]!,
                activeCubeCellPositions[i * 3 + 2]!,
            ],
            depth: 0,
            coveringResidual: safeR,
        }
    }
    const tLeavesAlloced = performance.now()

    // Level-by-level subdivision. A "marked" leaf splits into 8 children at depth+1.
    // The 8 children's cellPos = parent.cellPos * 2 + (octant offset 0..7 → (i&1, (i>>1)&1, (i>>2)&1)).
    let baseCubesRefined = 0
    const refinedBaseSet = new Set<number>() // pack (x, y, z) into a single key
    const packBaseKey = (x: number, y: number, z: number) =>
        (x | 0) + (y | 0) * nxBase + (z | 0) * (nxBase * nyBase)

    for (let level = 0; level < maxDepth; level++) {
        const nextLeaves: OctreeLeaf[] = []
        let levelMarks = 0

        for (const leaf of currentLeaves) {
            // Marked iff residual exceeds threshold AND we haven't bottomed out.
            // The threshold scaling stays constant across depths in this Session 1 — the
            // paper notes this matches their "function-error" criterion which is depth-
            // independent (a flat region stays flat at any sub-resolution). Session 2's
            // per-child residual recompute will let us drop the constant-threshold
            // assumption; for now it's a safe conservative choice.
            if (leaf.depth >= maxDepth || leaf.coveringResidual <= threshold) {
                nextLeaves.push(leaf)
                continue
            }
            levelMarks++

            // Track which base-grid cubes contributed to refinement (for stats).
            const baseScale = 1 << leaf.depth
            const baseX = (leaf.cellPos[0] / baseScale) | 0
            const baseY = (leaf.cellPos[1] / baseScale) | 0
            const baseZ = (leaf.cellPos[2] / baseScale) | 0
            const baseKey = packBaseKey(baseX, baseY, baseZ)
            if (!refinedBaseSet.has(baseKey)) {
                refinedBaseSet.add(baseKey)
                baseCubesRefined++
            }

            // Emit 8 children. Each child's cellPos at depth+1 = parent*2 + octant.
            const px = leaf.cellPos[0] * 2
            const py = leaf.cellPos[1] * 2
            const pz = leaf.cellPos[2] * 2
            for (let oct = 0; oct < 8; oct++) {
                nextLeaves.push({
                    cellPos: [
                        px + (oct & 1),
                        py + ((oct >> 1) & 1),
                        pz + ((oct >> 2) & 1),
                    ],
                    depth: leaf.depth + 1,
                    coveringResidual: leaf.coveringResidual, // see Session-1 inheritance note above
                })
            }
        }

        currentLeaves = nextLeaves
        if (levelMarks === 0) {
            // No more refinement; we're done.
            break
        }
    }
    const tRefined = performance.now()

    // Per-depth leaf histogram for logs.
    const leavesPerDepth = new Map<number, number>()
    for (const leaf of currentLeaves) {
        leavesPerDepth.set(leaf.depth, (leavesPerDepth.get(leaf.depth) ?? 0) + 1)
    }

    // Adaptivity ratio: how many leaves we have vs. what a uniform grid at maxDepth would
    // have generated. <1 = octree saves cells; 1 = no savings (refinement was universal).
    const equivalentUniformLeafCount = cubeCount * Math.pow(8, maxDepth)
    const adaptivityRatio = equivalentUniformLeafCount > 0
        ? currentLeaves.length / equivalentUniformLeafCount
        : 1

    const result: OctreeBuildResult = {
        leaves: currentLeaves,
        leavesPerDepth,
        baseCubesRefined,
        totalResidual,
        maxResidual,
        equivalentUniformLeafCount,
        adaptivityRatio,
        timingMs: {
            initialLeaves: Math.round((tLeavesAlloced - t0) * 100) / 100,
            refine: Math.round((tRefined - tLeavesAlloced) * 100) / 100,
            total: Math.round((tRefined - t0) * 100) / 100,
        },
    }
    return result
}

/**
 * Auto-tune the residual threshold so about `targetRefinedFraction` of samples would be
 * flagged for subdivision (those with **strictly larger** residual than the returned value).
 *
 * When many cubes have **exactly zero** QEF residual (flat cells), the global `(1−α)`
 * quantile can sit at `0`. Using `0` as the cutoff makes **every** positive residual
 * subdivide — often far more than the intended fraction and **orders of magnitude** too
 * many octree leaves (see IsoExport logs: threshold=`0.000e+0`, millions of sub-cells).
 *
 * In that case we rank **only strictly positive** residuals for the same fraction.
 */
export function pickResidualThresholdFromPercentile(
    residuals: Float32Array,
    targetRefinedFraction: number,
): number {
    const safeFraction = Math.max(0, Math.min(1, targetRefinedFraction))
    if (residuals.length === 0 || safeFraction === 0) return Infinity

    const sorted = new Float32Array(residuals)
    sorted.sort((a, b) => a - b)
    const n = sorted.length
    const maxV = sorted[n - 1]!
    if (!(maxV > 0)) return 0

    const k = Math.min(n, Math.max(1, Math.ceil(safeFraction * n)))
    const cut = n - k
    const tGlobal = cut > 0 ? sorted[cut - 1]! : -Infinity

    if (tGlobal > 0) return tGlobal

    // Zero-heavy: rank positives only so we approximate `safeFraction` of *positive* cubes.
    let posCount = 0
    for (let i = 0; i < n; i++) {
        if (sorted[i]! > 0) posCount++
    }
    if (posCount === 0) return 0

    const pos = new Float32Array(posCount)
    let w = 0
    for (let i = 0; i < n; i++) {
        const v = sorted[i]!
        if (v > 0) pos[w++] = v
    }
    pos.sort((a, b) => a - b)
    const kp = Math.min(posCount, Math.max(1, Math.ceil(safeFraction * posCount)))
    const cutp = posCount - kp
    return cutp > 0 ? pos[cutp - 1]! : 0
}

/**
 * Format the octree build result as a single human-readable line for `dbgLog` output.
 * Includes leaf totals, per-depth distribution, residual range, and adaptivity ratio.
 */
export function formatOctreeStats(result: OctreeBuildResult): string {
    const perDepth = Array.from(result.leavesPerDepth.entries())
        .sort((a, b) => a[0] - b[0])
        .map(([d, n]) => `d${d}=${n}`)
        .join(",")
    const ratioPct = (result.adaptivityRatio * 100).toFixed(2)
    const t = result.timingMs
    return `octree: leaves=${result.leaves.length} (${perDepth}), refined=${result.baseCubesRefined} base cubes, `
        + `residual sum=${result.totalResidual.toExponential(3)} max=${result.maxResidual.toExponential(3)}, `
        + `adaptivity=${ratioPct}% of uniform@maxDepth, CPU ${t.total} ms`
}

/** Convenience: log the octree statistics under the IsoExport debug module. */
export function logOctreeStats(result: OctreeBuildResult): void {
    dbgLog("IsoExport").debug(formatOctreeStats(result))
}

// ============================== Stage 4 Sessions 2, 5, 6 ==============================
// GPU sub-cube / sub-edge / sub-face dual placement — GLOBAL finest-lattice coordinates.
// `subMul = 2^octreeMaxDepth` stretches the virtual finest grid along each axis vs base
// cell counts (nx, ny, nz). WGSL mirrors these linear-index formulas using `mdcU0.z`.

/** A child sub-cube descriptor matching WGSL `childCubeInfo[i]` (vec4u) layout.
 *  Coordinates are GLOBAL finest-sub-grid min-corner indices.
 *  Word 3 = octree leaf depth (1..maxDepth). Pass 11 reads depth for sub-voxel sizing. */
export interface ChildCubeInfo {
    gsx: number
    gsy: number
    gsz: number
    depth: number
}

/** A child sub-edge descriptor matching WGSL `childEdgeInfo[i]` (vec4u) layout.
 *  Coordinates are GLOBAL sub-grid lo-corner positions; range depends on axis:
 *    X-edge: gsx ∈ [0, 2*nx),     gsy ∈ [0, 2*ny+1), gsz ∈ [0, 2*nz+1)
 *    Y-edge: gsx ∈ [0, 2*nx+1), gsy ∈ [0, 2*ny),     gsz ∈ [0, 2*nz+1)
 *    Z-edge: gsx ∈ [0, 2*nx+1), gsy ∈ [0, 2*ny+1), gsz ∈ [0, 2*nz)
 *  axis: 0 = X-edge, 1 = Y-edge, 2 = Z-edge. */
export interface ChildEdgeInfo {
    gsx: number
    gsy: number
    gsz: number
    axis: 0 | 1 | 2
}

/** A child sub-face descriptor matching WGSL `childFaceInfo[i]` (vec4u) layout.
 *  Coordinates are GLOBAL sub-grid min-corner positions; range depends on axis (the
 *  axis perpendicular to the face):
 *    YZ-face (axis=0): gsx ∈ [0, 2*nx+1), gsy ∈ [0, 2*ny),   gsz ∈ [0, 2*nz)
 *    XZ-face (axis=1): gsx ∈ [0, 2*nx),   gsy ∈ [0, 2*ny+1), gsz ∈ [0, 2*nz)
 *    XY-face (axis=2): gsx ∈ [0, 2*nx),   gsy ∈ [0, 2*ny),   gsz ∈ [0, 2*nz+1)
 *  axis: 0 = YZ-face (perp X), 1 = XZ-face (perp Y), 2 = XY-face (perp Z). */
export interface ChildFaceInfo {
    gsx: number
    gsy: number
    gsz: number
    axis: 0 | 1 | 2
}

// ---------- Linear-index formulas (CPU) for the sparse hash extension ----------
// Each sub-cell category maps a global sub-grid coord to a unique linear index. Must
// match `subCellLinearIdx*` helpers in `iso.wgsl` exactly (Session 6 work).

/** Linear index for a sub-cube at global finest-grid coords. `subMul = 2^octreeMaxDepth`. */
export function subCubeLinearIdx(
    gsx: number, gsy: number, gsz: number, nxBase: number, nyBase: number, subMul: number,
): number {
    const sx = subMul * nxBase
    const sy = subMul * nyBase
    return gsx + gsy * sx + gsz * sx * sy
}

/** Linear index for an X-sub-edge. */
export function subEdgeXLinearIdx(
    gsx: number, gsy: number, gsz: number, nxBase: number, nyBase: number, subMul: number,
): number {
    const sx = subMul * nxBase
    const sy = subMul * nyBase
    return gsx + gsy * sx + gsz * sx * (sy + 1)
}

/** Linear index for a Y-sub-edge. */
export function subEdgeYLinearIdx(
    gsx: number, gsy: number, gsz: number, nxBase: number, nyBase: number, subMul: number,
): number {
    const sx = subMul * nxBase + 1
    const sy = subMul * nyBase
    return gsx + gsy * sx + gsz * sx * sy
}

/** Linear index for a Z-sub-edge. */
export function subEdgeZLinearIdx(
    gsx: number, gsy: number, gsz: number, nxBase: number, nyBase: number, subMul: number,
): number {
    const sx = subMul * nxBase + 1
    const sy = subMul * nyBase + 1
    return gsx + gsy * sx + gsz * sx * sy
}

/** Linear index for a YZ-sub-face (perpendicular to X). */
export function subFaceYZLinearIdx(
    gsx: number, gsy: number, gsz: number, nxBase: number, nyBase: number, subMul: number,
): number {
    const sx = subMul * nxBase + 1
    const sy = subMul * nyBase
    return gsx + gsy * sx + gsz * sx * sy
}

/** Linear index for an XZ-sub-face (perpendicular to Y). */
export function subFaceXZLinearIdx(
    gsx: number, gsy: number, gsz: number, nxBase: number, nyBase: number, subMul: number,
): number {
    const sx = subMul * nxBase
    const sy = subMul * nyBase + 1
    return gsx + gsy * sx + gsz * sx * sy
}

/** Linear index for an XY-sub-face (perpendicular to Z). */
export function subFaceXYLinearIdx(
    gsx: number, gsy: number, gsz: number, nxBase: number, nyBase: number, subMul: number,
): number {
    const sx = subMul * nxBase
    const sy = subMul * nyBase
    return gsx + gsy * sx + gsz * sx * sy
}

export function subCubeLinearIdxBig(
    gsx: number, gsy: number, gsz: number, nxBase: number, nyBase: number, subMul: number,
): bigint {
    const sx = BigInt(subMul) * BigInt(nxBase)
    const sy = BigInt(subMul) * BigInt(nyBase)
    return BigInt(gsx) + BigInt(gsy) * sx + BigInt(gsz) * sx * sy
}

function subEdgeXLinearIdxBig(
    gsx: number, gsy: number, gsz: number, nxBase: number, nyBase: number, subMul: number,
): bigint {
    const sx = BigInt(subMul) * BigInt(nxBase)
    const sy = BigInt(subMul) * BigInt(nyBase)
    return BigInt(gsx) + BigInt(gsy) * sx + BigInt(gsz) * sx * (sy + 1n)
}

function subEdgeYLinearIdxBig(
    gsx: number, gsy: number, gsz: number, nxBase: number, nyBase: number, subMul: number,
): bigint {
    const sx = BigInt(subMul) * BigInt(nxBase) + 1n
    const sy = BigInt(subMul) * BigInt(nyBase)
    return BigInt(gsx) + BigInt(gsy) * sx + BigInt(gsz) * sx * sy
}

function subEdgeZLinearIdxBig(
    gsx: number, gsy: number, gsz: number, nxBase: number, nyBase: number, subMul: number,
): bigint {
    const sx = BigInt(subMul) * BigInt(nxBase) + 1n
    const sy = BigInt(subMul) * BigInt(nyBase) + 1n
    return BigInt(gsx) + BigInt(gsy) * sx + BigInt(gsz) * sx * sy
}

function subFaceYZLinearIdxBig(
    gsx: number, gsy: number, gsz: number, nxBase: number, nyBase: number, subMul: number,
): bigint {
    const sx = BigInt(subMul) * BigInt(nxBase) + 1n
    const sy = BigInt(subMul) * BigInt(nyBase)
    return BigInt(gsx) + BigInt(gsy) * sx + BigInt(gsz) * sx * sy
}

function subFaceXZLinearIdxBig(
    gsx: number, gsy: number, gsz: number, nxBase: number, nyBase: number, subMul: number,
): bigint {
    const sx = BigInt(subMul) * BigInt(nxBase)
    const sy = BigInt(subMul) * BigInt(nyBase) + 1n
    return BigInt(gsx) + BigInt(gsy) * sx + BigInt(gsz) * sx * sy
}

function subFaceXYLinearIdxBig(
    gsx: number, gsy: number, gsz: number, nxBase: number, nyBase: number, subMul: number,
): bigint {
    const sx = BigInt(subMul) * BigInt(nxBase)
    const sy = BigInt(subMul) * BigInt(nyBase)
    return BigInt(gsx) + BigInt(gsy) * sx + BigInt(gsz) * sx * sy
}

function emitLeafSubEdgesInto(
    leaf: OctreeLeaf,
    maxDepth: number,
    nxBase: number,
    nyBase: number,
    subMul: number,
    seenX: Set<bigint>,
    seenY: Set<bigint>,
    seenZ: Set<bigint>,
    edges: ChildEdgeInfo[],
): void {
    if (leaf.depth === 0) return
    const span = 1 << (maxDepth - leaf.depth)
    const ox = leaf.cellPos[0] * span
    const oy = leaf.cellPos[1] * span
    const oz = leaf.cellPos[2] * span
    for (let gx = ox; gx < ox + span; gx++) {
        for (let gy = oy; gy <= oy + span; gy++) {
            for (let gz = oz; gz <= oz + span; gz++) {
                const lin = subEdgeXLinearIdxBig(gx, gy, gz, nxBase, nyBase, subMul)
                if (seenX.has(lin)) continue
                seenX.add(lin)
                edges.push({ gsx: gx, gsy: gy, gsz: gz, axis: 0 })
            }
        }
    }
    for (let gx = ox; gx <= ox + span; gx++) {
        for (let gy = oy; gy < oy + span; gy++) {
            for (let gz = oz; gz <= oz + span; gz++) {
                const lin = subEdgeYLinearIdxBig(gx, gy, gz, nxBase, nyBase, subMul)
                if (seenY.has(lin)) continue
                seenY.add(lin)
                edges.push({ gsx: gx, gsy: gy, gsz: gz, axis: 1 })
            }
        }
    }
    for (let gx = ox; gx <= ox + span; gx++) {
        for (let gy = oy; gy <= oy + span; gy++) {
            for (let gz = oz; gz < oz + span; gz++) {
                const lin = subEdgeZLinearIdxBig(gx, gy, gz, nxBase, nyBase, subMul)
                if (seenZ.has(lin)) continue
                seenZ.add(lin)
                edges.push({ gsx: gx, gsy: gy, gsz: gz, axis: 2 })
            }
        }
    }
}

function emitLeafSubFacesInto(
    leaf: OctreeLeaf,
    maxDepth: number,
    nxBase: number,
    nyBase: number,
    subMul: number,
    seenYZ: Set<bigint>,
    seenXZ: Set<bigint>,
    seenXY: Set<bigint>,
    faces: ChildFaceInfo[],
): void {
    if (leaf.depth === 0) return
    const span = 1 << (maxDepth - leaf.depth)
    const ox = leaf.cellPos[0] * span
    const oy = leaf.cellPos[1] * span
    const oz = leaf.cellPos[2] * span
    for (let gx = ox; gx <= ox + span; gx++) {
        for (let gy = oy; gy < oy + span; gy++) {
            for (let gz = oz; gz < oz + span; gz++) {
                const lin = subFaceYZLinearIdxBig(gx, gy, gz, nxBase, nyBase, subMul)
                if (seenYZ.has(lin)) continue
                seenYZ.add(lin)
                faces.push({ gsx: gx, gsy: gy, gsz: gz, axis: 0 })
            }
        }
    }
    for (let gx = ox; gx < ox + span; gx++) {
        for (let gy = oy; gy <= oy + span; gy++) {
            for (let gz = oz; gz < oz + span; gz++) {
                const lin = subFaceXZLinearIdxBig(gx, gy, gz, nxBase, nyBase, subMul)
                if (seenXZ.has(lin)) continue
                seenXZ.add(lin)
                faces.push({ gsx: gx, gsy: gy, gsz: gz, axis: 1 })
            }
        }
    }
    for (let gx = ox; gx < ox + span; gx++) {
        for (let gy = oy; gy < oy + span; gy++) {
            for (let gz = oz; gz <= oz + span; gz++) {
                const lin = subFaceXYLinearIdxBig(gx, gy, gz, nxBase, nyBase, subMul)
                if (seenXY.has(lin)) continue
                seenXY.add(lin)
                faces.push({ gsx: gx, gsy: gy, gsz: gz, axis: 2 })
            }
        }
    }
}

/**
 * Emit one child cube per refined octree leaf, mapped to GLOBAL finest-grid coordinates.
 */
export function buildChildCubeListFromOctree(octree: OctreeBuildResult, maxDepth: number): {
    children: ChildCubeInfo[]
    skippedDeeperLeaves: number
} {
    const children: ChildCubeInfo[] = []
    let skippedDeeperLeaves = 0

    for (const leaf of octree.leaves) {
        if (leaf.depth === 0) continue
        if (leaf.depth > maxDepth) {
            skippedDeeperLeaves++
            continue
        }
        const scale = 1 << (maxDepth - leaf.depth)
        children.push({
            gsx: leaf.cellPos[0] * scale,
            gsy: leaf.cellPos[1] * scale,
            gsz: leaf.cellPos[2] * scale,
            depth: leaf.depth,
        })
    }

    return { children, skippedDeeperLeaves }
}

/** Stride in u32 of one packed `ChildCubeInfo` entry — must match `vec4u` layout. */
export const CHILD_CUBE_INFO_STRIDE_U32 = 4

/** Pack the child-cube list into a Uint32Array for GPU upload.
 *  Layout: vec4u(gsx, gsy, gsz, depth). */
export function packChildCubeInfo(children: ChildCubeInfo[]): Uint32Array {
    const packed = new Uint32Array(children.length * CHILD_CUBE_INFO_STRIDE_U32)
    for (let i = 0; i < children.length; i++) {
        const c = children[i]!
        packed[i * CHILD_CUBE_INFO_STRIDE_U32] = c.gsx >>> 0
        packed[i * CHILD_CUBE_INFO_STRIDE_U32 + 1] = c.gsy >>> 0
        packed[i * CHILD_CUBE_INFO_STRIDE_U32 + 2] = c.gsz >>> 0
        packed[i * CHILD_CUBE_INFO_STRIDE_U32 + 3] = c.depth >>> 0
    }
    return packed
}

/** Enumerate unique finest-grid sub-edges required by every refined octree leaf. */
export function buildChildEdgeListFromOctree(
    octree: OctreeBuildResult,
    nxBase: number,
    nyBase: number,
    maxDepth: number,
): {
    edges: ChildEdgeInfo[]
    skippedDeeperLeaves: number
} {
    const edges: ChildEdgeInfo[] = []
    let skippedDeeperLeaves = 0
    const subMul = subAxisMulFromMaxDepth(maxDepth)
    const seenX = new Set<bigint>()
    const seenY = new Set<bigint>()
    const seenZ = new Set<bigint>()
    for (const leaf of octree.leaves) {
        if (leaf.depth === 0) continue
        if (leaf.depth > maxDepth) {
            skippedDeeperLeaves++
            continue
        }
        emitLeafSubEdgesInto(leaf, maxDepth, nxBase, nyBase, subMul, seenX, seenY, seenZ, edges)
    }
    return { edges, skippedDeeperLeaves }
}

/** Enumerate unique finest-grid sub-faces required by every refined octree leaf. */
export function buildChildFaceListFromOctree(
    octree: OctreeBuildResult,
    nxBase: number,
    nyBase: number,
    maxDepth: number,
): {
    faces: ChildFaceInfo[]
    skippedDeeperLeaves: number
} {
    const faces: ChildFaceInfo[] = []
    let skippedDeeperLeaves = 0
    const subMul = subAxisMulFromMaxDepth(maxDepth)
    const seenYZ = new Set<bigint>()
    const seenXZ = new Set<bigint>()
    const seenXY = new Set<bigint>()
    for (const leaf of octree.leaves) {
        if (leaf.depth === 0) continue
        if (leaf.depth > maxDepth) {
            skippedDeeperLeaves++
            continue
        }
        emitLeafSubFacesInto(leaf, maxDepth, nxBase, nyBase, subMul, seenYZ, seenXZ, seenXY, faces)
    }
    return { faces, skippedDeeperLeaves }
}

/** Pack a `ChildEdgeInfo[]` for GPU upload. Layout: vec4u(gsx, gsy, gsz, axis). */
export function packChildEdgeInfo(edges: ChildEdgeInfo[]): Uint32Array {
    const packed = new Uint32Array(edges.length * 4)
    for (let i = 0; i < edges.length; i++) {
        const e = edges[i]!
        packed[i * 4] = e.gsx >>> 0
        packed[i * 4 + 1] = e.gsy >>> 0
        packed[i * 4 + 2] = e.gsz >>> 0
        packed[i * 4 + 3] = e.axis & 3
    }
    return packed
}

/** Pack a `ChildFaceInfo[]` for GPU upload. Layout: vec4u(gsx, gsy, gsz, axis). */
export function packChildFaceInfo(faces: ChildFaceInfo[]): Uint32Array {
    const packed = new Uint32Array(faces.length * 4)
    for (let i = 0; i < faces.length; i++) {
        const f = faces[i]!
        packed[i * 4] = f.gsx >>> 0
        packed[i * 4 + 1] = f.gsy >>> 0
        packed[i * 4 + 2] = f.gsz >>> 0
        packed[i * 4 + 3] = f.axis & 3
    }
    return packed
}

// ============================== Stage 4 Session 6: sub-cell sparse hash builder ==============================

/** Cell-type IDs for sub-cells in the depth-aware sparse hash key. Must match the
 *  WGSL `CELL_TYPE_SUB_*` constants in `iso.wgsl`. Base cell types (0..7) are
 *  re-exported from `iso-sparse.mts`. */
export const CELL_TYPE_SUB_CUBE = 8
export const CELL_TYPE_SUB_EDGE_X = 9
export const CELL_TYPE_SUB_EDGE_Y = 10
export const CELL_TYPE_SUB_EDGE_Z = 11
export const CELL_TYPE_SUB_FACE_YZ = 12
export const CELL_TYPE_SUB_FACE_XZ = 13
export const CELL_TYPE_SUB_FACE_XY = 14

/** Sub-cell sparse hash table built from the deduped sub-cell descriptor lists.
 *  Each entry maps `(subCellType, sub_grid_linearIdx)` → ABSOLUTE slot index in the
 *  unified `subCellAllDuals` buffer (Stage 4 Session 7). The `subCubeBase`,
 *  `subEdgeBase`, `subFaceBase` fields tell the orchestrator the per-pass write
 *  offsets to upload to `uniforms.subCellBases`. */
export interface SubCellSparseHash {
    /** Open-addressed `(key_lo, key_hi, slot, _)` rows; matches WGSL `subDualHashTable` vec4u layout. */
    hashTable: Uint32Array
    /** Power-of-two entry count = `hashTable.length / 4`. */
    hashEntries: number
    /** `hashEntries - 1`; passed to WGSL as `uniforms.subSparseHash.x`. */
    hashMask: number
    /** Total slots inserted = subCubeCount + subEdgeCount + subFaceCount. */
    totalSlots: number
    /** Absolute write base for sub-cubes in `subCellAllDuals` (always 0). */
    subCubeBase: number
    /** Absolute write base for sub-edges = subCubeCount. */
    subEdgeBase: number
    /** Absolute write base for sub-faces = subCubeCount + subEdgeCount. */
    subFaceBase: number
}

const SUB_HASH_KNUTH = SPARSE_HASH_KNUTH
const SUB_HASH_KEY_EMPTY = 0xffffffff

/**
 * Build the sub-cell sparse hash table from the deduplicated descriptor lists.
 *
 * Stage 4 Session 7: slot is now an ABSOLUTE index into the unified
 * `subCellAllDuals` GPU buffer. Layout:
 *   slots [0,                          numSubCubes)  — sub-cubes
 *   slots [numSubCubes,                numSubCubes + numSubEdges)  — sub-edges
 *   slots [numSubCubes + numSubEdges,  total)  — sub-faces
 *
 * Pass 11/12/13 write to `subCellAllDuals[base + dispatch_index]` where bases are
 * supplied via `uniforms.subCellBases`. The hash builder mirrors that base addressing.
 *
 * Hash capacity: `next_power_of_two(2 × totalSlots)` — 50% load factor.
 */
export function buildSubCellSparseHash(
    subCubes: ChildCubeInfo[],
    subEdges: ChildEdgeInfo[],
    subFaces: ChildFaceInfo[],
    nxBase: number,
    nyBase: number,
    subMul: number,
): SubCellSparseHash {
    const totalSlots = subCubes.length + subEdges.length + subFaces.length
    const subCubeBase = 0
    const subEdgeBase = subCubes.length
    const subFaceBase = subCubes.length + subEdges.length

    // Empty case: return a 1-entry-marked-empty hash so the WGSL `mask == 0u` early-out
    // path takes effect cleanly.
    if (totalSlots === 0) {
        const hashTable = new Uint32Array(4)
        hashTable.fill(SUB_HASH_KEY_EMPTY)
        return {
            hashTable, hashEntries: 1, hashMask: 0, totalSlots: 0,
            subCubeBase, subEdgeBase, subFaceBase,
        }
    }

    let hashEntries = 1
    const target = Math.max(64, totalSlots * 4)
    while (hashEntries < target) hashEntries <<= 1
    const hashMask = hashEntries - 1
    const hashTable = new Uint32Array(hashEntries * 4)
    hashTable.fill(SUB_HASH_KEY_EMPTY)

    const insertHash = (keyLo: number, keyHi: number, slot: number) => {
        let probe = (
            (Math.imul(keyLo >>> 0, SUB_HASH_KNUTH) >>> 0)
            ^ (Math.imul(keyHi >>> 0, SPARSE_HASH_KNUTH_HI) >>> 0)
        ) & hashMask
        for (let i = 0; i < 4096; i++) {
            const base4 = probe * 4
            if (hashTable[base4] === SUB_HASH_KEY_EMPTY && hashTable[base4 + 1] === SUB_HASH_KEY_EMPTY) {
                hashTable[base4] = keyLo >>> 0
                hashTable[base4 + 1] = keyHi >>> 0
                hashTable[base4 + 2] = slot >>> 0
                hashTable[base4 + 3] = 0
                return
            }
            probe = (probe + 1) & hashMask
        }
        throw new Error(
            `Sub-cell sparse hash insert overflowed 4096 probes at keyLo=${keyLo} keyHi=${keyHi}, slot=${slot}; `
            + `entries=${hashEntries}, totalSlots=${totalSlots}`,
        )
    }

    // Sub-cubes: slot = subCubeBase + index in subCubes[].
    for (let i = 0; i < subCubes.length; i++) {
        const c = subCubes[i]!
        const linear = subCubeLinearIdxBig(c.gsx, c.gsy, c.gsz, nxBase, nyBase, subMul)
        const { keyLo, keyHi } = encodeSparseDualHashKeyBigInt(CELL_TYPE_SUB_CUBE, linear)
        insertHash(keyLo, keyHi, subCubeBase + i)
    }
    for (let i = 0; i < subEdges.length; i++) {
        const e = subEdges[i]!
        let linear: bigint
        if (e.axis === 0) {
            linear = subEdgeXLinearIdxBig(e.gsx, e.gsy, e.gsz, nxBase, nyBase, subMul)
        } else if (e.axis === 1) {
            linear = subEdgeYLinearIdxBig(e.gsx, e.gsy, e.gsz, nxBase, nyBase, subMul)
        } else {
            linear = subEdgeZLinearIdxBig(e.gsx, e.gsy, e.gsz, nxBase, nyBase, subMul)
        }
        const { keyLo, keyHi } = encodeSparseDualHashKeyBigInt(
            e.axis === 0 ? CELL_TYPE_SUB_EDGE_X : e.axis === 1 ? CELL_TYPE_SUB_EDGE_Y : CELL_TYPE_SUB_EDGE_Z,
            linear,
        )
        insertHash(keyLo, keyHi, subEdgeBase + i)
    }
    for (let i = 0; i < subFaces.length; i++) {
        const f = subFaces[i]!
        let linear: bigint
        if (f.axis === 0) {
            linear = subFaceYZLinearIdxBig(f.gsx, f.gsy, f.gsz, nxBase, nyBase, subMul)
        } else if (f.axis === 1) {
            linear = subFaceXZLinearIdxBig(f.gsx, f.gsy, f.gsz, nxBase, nyBase, subMul)
        } else {
            linear = subFaceXYLinearIdxBig(f.gsx, f.gsy, f.gsz, nxBase, nyBase, subMul)
        }
        const { keyLo, keyHi } = encodeSparseDualHashKeyBigInt(
            f.axis === 0 ? CELL_TYPE_SUB_FACE_YZ : f.axis === 1 ? CELL_TYPE_SUB_FACE_XZ : CELL_TYPE_SUB_FACE_XY,
            linear,
        )
        insertHash(keyLo, keyHi, subFaceBase + i)
    }

    return { hashTable, hashEntries, hashMask, totalSlots, subCubeBase, subEdgeBase, subFaceBase }
}

/**
 * Compute summary statistics about an array of QEF residuals (parent or child).
 * Useful for "did refinement help?" comparisons in the diagnostic log: if the
 * child residual distribution is significantly LOWER than the parent residuals
 * for the same cubes, the refinement is mathematically working — each sub-cube
 * fits the local SDF tangent planes better than the parent did.
 */
export function summarizeResidualDistribution(residuals: Float32Array | number[]): {
    count: number
    sum: number
    max: number
    mean: number
    /** P50 of finite, non-negative residuals. */
    median: number
    /** P95 of finite, non-negative residuals. */
    p95: number
} {
    let count = 0
    let sum = 0
    let max = 0
    const sorted: number[] = []
    for (let i = 0; i < residuals.length; i++) {
        const v = residuals[i]!
        if (!Number.isFinite(v) || v < 0) continue
        count++
        sum += v
        if (v > max) max = v
        sorted.push(v)
    }
    sorted.sort((a, b) => a - b)
    const median = count > 0 ? (sorted[Math.floor(count * 0.5)] ?? 0) : 0
    const p95 = count > 0 ? (sorted[Math.floor(count * 0.95)] ?? 0) : 0
    const mean = count > 0 ? sum / count : 0
    return { count, sum, max, mean, median, p95 }
}

// ============================== Phase 5 (Session 9): minimal-cube enumeration ==============================
//
// `buildMinimalCubeList` enumerates the cubes that Pass 15 (multi-resolution MT) must walk:
//
//   1. Every depth-1 sub-cube of every refined parent (8 per parent). These are the
//      sub-cubes themselves; they're "minimal" because their parent is no longer minimal.
//   2. Every active depth-0 base cube that has a refined cube as a face- or edge-neighbour
//      (= within Manhattan distance √2). These cubes themselves are still depth-0 minimal,
//      but at least one of their 12 base edges has a refined cube around it, so Pass 6
//      skips that edge in adaptive mode and Pass 15 must emit those tets.
//
// Pass 6 and Pass 15 form a partition of mesh emission: an active base cube C is processed
// either by Pass 6 (when no neighbour is refined within edge-share distance) or by Pass 15
// (when at least one is). The two never both emit for the same minimal cube.
//
// Coordinate convention: every minimal cube descriptor stores SUB-grid coords:
//   - Depth-0 (unrefined): gsx = 2*cx, gsy = 2*cy, gsz = 2*cz. The cube spans sub-grid
//     positions [2*cx, 2*cx+2). This matches the depth-1 convention so the WGSL walk
//     code is uniform.
//   - Depth-1 (sub-cube): gsx = sub-cube's actual sub-grid x. Cube spans [gsx, gsx+1).
//
// Per-descriptor packed layout (16 bytes = 1 vec4u, suitable for packing into the tail of
// `subCellAllDuals` alongside other Stage-4 sub-cell data):
//   word 0: gsx
//   word 1: gsy
//   word 2: gsz
//   word 3: bit 0       = depth (0 or 1)
//           bits 1..6   = neighbourRefinedMask (only meaningful for depth=0)
//                         bit  0 = -X, 1 = +X, 2 = -Y, 3 = +Y, 4 = -Z, 5 = +Z
//                         (after the depth bit, so positions 1..6 in the u32)
//           bits 7..    = reserved
//
// The neighbourRefinedMask only covers FACE neighbours (6 directions). Edge-neighbour
// refinement (12 directions) is queried per-base-edge by the WGSL shader using its own
// `is_base_cube_refined` helper; tracking it CPU-side would 4x the descriptor size for
// no gain.

export interface MinimalCubeListResult {
    /** Packed `vec4u` per minimal cube. Length = numMinimalCubes × 4. */
    descriptors: Uint32Array
    /** Number of minimal-cube descriptors (= descriptors.length / 4). */
    numMinimalCubes: number
    /** How many depth-0 unrefined-but-pass15-territory cubes are in `descriptors`. */
    numDepth0: number
    /** How many depth-1 sub-cubes are in `descriptors`. */
    numDepth1: number
}

/**
 * Build the minimal-cube list for Pass 15 dispatch.
 *
 * `octreeChildren` comes from `buildChildCubeListFromOctree` (finest-grid coords + depth).
 */
export function buildMinimalCubeList(
    octreeChildren: ChildCubeInfo[],
    activeCubeCompactList: Uint32Array,
    nxBase: number,
    nyBase: number,
    nzBase: number,
    maxDepth: number,
): MinimalCubeListResult {
    const S = subAxisMulFromMaxDepth(maxDepth)
    // Step 1: refined base cubes (each child implies its base parent is refined).
    const refinedParentBits = new Uint32Array(Math.max(1, Math.ceil(nxBase * nyBase * nzBase / 32)))
    const refinedParentSet = new Set<number>()
    for (const c of octreeChildren) {
        const px = Math.floor(c.gsx / S)
        const py = Math.floor(c.gsy / S)
        const pz = Math.floor(c.gsz / S)
        const linear = px + py * nxBase + pz * nxBase * nyBase
        if (refinedParentSet.has(linear)) continue
        refinedParentSet.add(linear)
        refinedParentBits[Math.floor(linear / 32)]! |= 1 << (linear % 32)
    }

    const isRefined = (cx: number, cy: number, cz: number): boolean => {
        if (cx < 0 || cx >= nxBase || cy < 0 || cy >= nyBase || cz < 0 || cz >= nzBase) return false
        const linear = cx + cy * nxBase + cz * nxBase * nyBase
        return (refinedParentBits[Math.floor(linear / 32)]! & (1 << (linear % 32))) !== 0
    }

    // Step 2: build a bitset of "Pass 15 territory" depth-0 cubes — the unrefined base
    // cubes that have at least one of their 12 base edges with a refined neighbour. We
    // dilate the refined set by the 18 face/edge-neighbour offsets (NOT the 8 corner-only
    // offsets — corner-neighbours don't share any base edge with C, so their refinement
    // doesn't force C into Pass 15 territory).
    const pass15TerritoryBits = new Uint32Array(refinedParentBits.length)
    const dilateOffsets: Array<[number, number, number]> = []
    for (let dx = -1; dx <= 1; dx++) {
        for (let dy = -1; dy <= 1; dy++) {
            for (let dz = -1; dz <= 1; dz++) {
                if (dx === 0 && dy === 0 && dz === 0) continue
                const absSum = Math.abs(dx) + Math.abs(dy) + Math.abs(dz)
                // Skip pure-corner offsets (|dx|+|dy|+|dz| == 3) — those neighbours share
                // only a corner with the centre cube and don't constrain Pass 15 territory.
                if (absSum >= 3) continue
                dilateOffsets.push([dx, dy, dz])
            }
        }
    }
    // dilateOffsets has 6 face + 12 edge = 18 entries.
    for (const linear of refinedParentSet) {
        const cz = Math.floor(linear / (nxBase * nyBase))
        const cy = Math.floor((linear - cz * nxBase * nyBase) / nxBase)
        const cx = linear - cy * nxBase - cz * nxBase * nyBase
        for (const [dx, dy, dz] of dilateOffsets) {
            const nx = cx + dx, ny = cy + dy, nz = cz + dz
            if (nx < 0 || nx >= nxBase || ny < 0 || ny >= nyBase || nz < 0 || nz >= nzBase) continue
            const nLinear = nx + ny * nxBase + nz * nxBase * nyBase
            // Skip if neighbour itself is refined — those are handled as depth-1 sub-cubes.
            if (refinedParentSet.has(nLinear)) continue
            pass15TerritoryBits[Math.floor(nLinear / 32)]! |= 1 << (nLinear % 32)
        }
    }

    // Step 3: walk active base cubes (sparse.cubeCompactList) and emit minimal-cube
    // descriptors for the ones that need Pass 15:
    //   - Refined base cube → one descriptor per finest leaf in `octreeChildren` under it
    //   - Unrefined AND in pass15Territory → 1 descriptor (bit0=0), LL corner scaled by S
    const out: number[] = []
    let numDepth0 = 0, numDepth1 = 0
    for (let i = 0; i < activeCubeCompactList.length; i++) {
        const linear = activeCubeCompactList[i]!
        const cx = linear % nxBase
        const cy = Math.floor(linear / nxBase) % nyBase
        const cz = Math.floor(linear / (nxBase * nyBase))
        if (refinedParentSet.has(linear)) {
            for (const c of octreeChildren) {
                if (Math.floor(c.gsx / S) !== cx || Math.floor(c.gsy / S) !== cy || Math.floor(c.gsz / S) !== cz) {
                    continue
                }
                out.push(c.gsx, c.gsy, c.gsz, (1 | (c.depth << 8)) >>> 0)
                numDepth1++
            }
            continue
        }
        const wordIdx = Math.floor(linear / 32)
        const bitIdx = linear % 32
        if ((pass15TerritoryBits[wordIdx]! & (1 << bitIdx)) === 0) continue

        let mask = 0
        if (isRefined(cx - 1, cy, cz)) mask |= 1 << 0
        if (isRefined(cx + 1, cy, cz)) mask |= 1 << 1
        if (isRefined(cx, cy - 1, cz)) mask |= 1 << 2
        if (isRefined(cx, cy + 1, cz)) mask |= 1 << 3
        if (isRefined(cx, cy, cz - 1)) mask |= 1 << 4
        if (isRefined(cx, cy, cz + 1)) mask |= 1 << 5
        const word3 = 0 | (mask << 1)
        out.push(cx * S, cy * S, cz * S, word3)
        numDepth0++
    }

    return {
        descriptors: new Uint32Array(out),
        numMinimalCubes: numDepth0 + numDepth1,
        numDepth0,
        numDepth1,
    }
}
