/**
 * Stage 4 (Manson & Schaefer §5.1) — adaptive octree foundation.
 *
 * Session 1 (current file): CPU-side octree representation built from the per-cube QEF
 * residual readback after `placeCubeDuals_Pass5`. The octree's leaves identify which
 * uniform-grid cubes the paper would subdivide for finer dual placement. Statistics are
 * logged for verification but the mesh output is unchanged in this session — multi-
 * resolution Marching Tetrahedra (Session 2+) will consume the leaf list.
 *
 * Why CPU for now: the per-level subdivision loop needs at minimum a per-level readback
 * to know how many leaves remain (so the dispatch-on-marked-leaves child allocator
 * doesn't dispatch over an empty set). For a small initial set of "subdivide candidates"
 * the readback overhead dominates GPU runtime anyway, so doing the bookkeeping CPU-side
 * is the cleanest first cut. Sessions 2+ will move the per-level loop to the GPU once
 * the multi-resolution dual-placement passes are in place.
 *
 * Octree node layout (one per leaf — interior nodes are not retained):
 *   - cellPos: vec3u — base-grid cube position at this leaf's depth (each level halves
 *     the voxel size, so a depth-2 leaf has cellPos in [0, 4×nx) × ...)
 *   - depth: number — 0 = base uniform grid; 1 = first refinement; 2 = second; ...
 *   - parentResidual: number — the QEF residual that triggered subdivision (informative).
 *
 * The leaf list is the union of:
 *   1. Base-grid cubes that were below the residual threshold (no subdivision needed)
 *   2. All sub-cubes generated by recursive subdivision of high-residual ancestors,
 *      down to the leaves at min(maxDepth, refinement-stops-when-no-more-marks).
 */

import { log as dbgLog } from "../logging/debug-log.mjs"

/** A leaf cube in the adaptive octree. Coordinates are at depth-resolution (each
 *  refinement level halves the voxel size, so cellPos / 2^depth gives base coords). */
export interface OctreeLeaf {
    /** Cube min-corner position at this leaf's depth resolution.
     *  At depth `d`, cellPos.x is in `[0, nx_base * 2^d)`. */
    cellPos: [number, number, number]
    /** 0 = base uniform grid; positive = refinement levels below base. */
    depth: number
    /** QEF residual at the dual position of the COVERING base cube. Useful for
     *  visualising which leaves came from refinement vs. were "good enough" at base. */
    coveringResidual: number
}

export interface OctreeBuildResult {
    /** All leaves in the adaptive octree (mix of base + refined depths). */
    leaves: OctreeLeaf[]
    /** Total leaf count per depth bucket (depth → count). */
    leavesPerDepth: Map<number, number>
    /** How many base-grid cubes were marked for subdivision at any level. */
    baseCubesRefined: number
    /** Total residual sum (CPU-side stat for relative cross-mesh comparison). */
    totalResidual: number
    /** Maximum residual observed (helps users tune `octreeResidualThreshold`). */
    maxResidual: number
    /** Number of leaves the equivalent UNIFORM grid at maxDepth would have produced
     *  (= base cube count × 8^maxDepth). Used to compute adaptivity ratio in logs. */
    equivalentUniformLeafCount: number
    /** Adaptivity ratio = leaves.length / equivalentUniformLeafCount. <1 = octree saves
     *  cells; closer to 1 = uniform-equivalent (refinement was widespread). */
    adaptivityRatio: number
    /** Per-step CPU timing (ms). */
    timingMs: Record<string, number>
}

/**
 * Build the adaptive octree from per-cube QEF residuals (session 1: CPU-only).
 *
 * Algorithm (paper §5.1, top-down):
 *   1. Start with the base uniform grid as level-0 leaves.
 *   2. For each level L (0 ≤ L < maxDepth):
 *      a. For each leaf at depth L, mark for subdivision iff
 *         coveringResidual > threshold AND depth < maxDepth.
 *      b. Each marked leaf produces 8 children at depth L+1 (Morton octant offsets).
 *      c. Children inherit the parent's residual as `coveringResidual` for their next
 *         subdivision check (in this CPU-only session — Session 2 will compute fresh
 *         per-child residuals on the GPU after sub-cube dual placement).
 *   3. Stop when no leaves are marked or all leaves hit maxDepth.
 *
 * Note on "covering residual" inheritance: a true paper implementation would re-compute
 * the QEF residual at each new sub-cube level (which requires GPU sub-cube dual
 * placement, deferred to Session 2). In Session 1 we use the parent's residual as a
 * conservative upper bound for the children — if parent says "subdivide", all 8
 * children also "want to subdivide" all the way down. This means Session 1's leaf set
 * is a strict superset of what the full algorithm would produce; Session 2 will prune
 * via per-child residuals.
 */
export function buildOctreeFromCubeResiduals(
    activeCubeCellPositions: Uint32Array, // packed [x0, y0, z0, x1, y1, z1, ...]
    cubeResiduals: Float32Array,           // one f32 per active cube (matches Pass 5 local_slot)
    nxBase: number,
    nyBase: number,
    nzBase: number,
    threshold: number,
    maxDepth: number,
): OctreeBuildResult {
    const t0 = performance.now()
    const cubeCount = (activeCubeCellPositions.length / 3) | 0
    if (cubeResiduals.length < cubeCount) {
        throw new Error(
            `iso-octree: cubeResiduals length (${cubeResiduals.length}) is less than `
            + `active cube count (${cubeCount}); upstream Pass 5 buffer mismatch?`,
        )
    }

    // Initial leaves at depth 0 — every active cube becomes a leaf with its own residual.
    // We retain inactive cubes implicitly: they're absent from `activeCubeCellPositions`
    // and contribute neither to the octree nor (by definition) to the iso surface.
    let currentLeaves: OctreeLeaf[] = new Array(cubeCount)
    let totalResidual = 0
    let maxResidual = 0
    for (let i = 0; i < cubeCount; i++) {
        const r = cubeResiduals[i]!
        const safeR = Number.isFinite(r) ? Math.max(0, r) : 0
        totalResidual += safeR
        if (safeR > maxResidual) maxResidual = safeR
        currentLeaves[i] = {
            cellPos: [
                activeCubeCellPositions[i * 3]!,
                activeCubeCellPositions[i * 3 + 1]!,
                activeCubeCellPositions[i * 3 + 2]!,
            ],
            depth: 0,
            coveringResidual: safeR,
        }
    }
    const tLeavesAlloced = performance.now()

    // Level-by-level subdivision. A "marked" leaf splits into 8 children at depth+1.
    // The 8 children's cellPos = parent.cellPos * 2 + (octant offset 0..7 → (i&1, (i>>1)&1, (i>>2)&1)).
    let baseCubesRefined = 0
    const refinedBaseSet = new Set<number>() // pack (x, y, z) into a single key
    const packBaseKey = (x: number, y: number, z: number) =>
        (x | 0) + (y | 0) * nxBase + (z | 0) * (nxBase * nyBase)

    for (let level = 0; level < maxDepth; level++) {
        const nextLeaves: OctreeLeaf[] = []
        let levelMarks = 0

        for (const leaf of currentLeaves) {
            // Marked iff residual exceeds threshold AND we haven't bottomed out.
            // The threshold scaling stays constant across depths in this Session 1 — the
            // paper notes this matches their "function-error" criterion which is depth-
            // independent (a flat region stays flat at any sub-resolution). Session 2's
            // per-child residual recompute will let us drop the constant-threshold
            // assumption; for now it's a safe conservative choice.
            if (leaf.depth >= maxDepth || leaf.coveringResidual <= threshold) {
                nextLeaves.push(leaf)
                continue
            }
            levelMarks++

            // Track which base-grid cubes contributed to refinement (for stats).
            const baseScale = 1 << leaf.depth
            const baseX = (leaf.cellPos[0] / baseScale) | 0
            const baseY = (leaf.cellPos[1] / baseScale) | 0
            const baseZ = (leaf.cellPos[2] / baseScale) | 0
            const baseKey = packBaseKey(baseX, baseY, baseZ)
            if (!refinedBaseSet.has(baseKey)) {
                refinedBaseSet.add(baseKey)
                baseCubesRefined++
            }

            // Emit 8 children. Each child's cellPos at depth+1 = parent*2 + octant.
            const px = leaf.cellPos[0] * 2
            const py = leaf.cellPos[1] * 2
            const pz = leaf.cellPos[2] * 2
            for (let oct = 0; oct < 8; oct++) {
                nextLeaves.push({
                    cellPos: [
                        px + (oct & 1),
                        py + ((oct >> 1) & 1),
                        pz + ((oct >> 2) & 1),
                    ],
                    depth: leaf.depth + 1,
                    coveringResidual: leaf.coveringResidual, // see Session-1 inheritance note above
                })
            }
        }

        currentLeaves = nextLeaves
        if (levelMarks === 0) {
            // No more refinement; we're done.
            break
        }
    }
    const tRefined = performance.now()

    // Per-depth leaf histogram for logs.
    const leavesPerDepth = new Map<number, number>()
    for (const leaf of currentLeaves) {
        leavesPerDepth.set(leaf.depth, (leavesPerDepth.get(leaf.depth) ?? 0) + 1)
    }

    // Adaptivity ratio: how many leaves we have vs. what a uniform grid at maxDepth would
    // have generated. <1 = octree saves cells; 1 = no savings (refinement was universal).
    const equivalentUniformLeafCount = cubeCount * Math.pow(8, maxDepth)
    const adaptivityRatio = equivalentUniformLeafCount > 0
        ? currentLeaves.length / equivalentUniformLeafCount
        : 1

    const result: OctreeBuildResult = {
        leaves: currentLeaves,
        leavesPerDepth,
        baseCubesRefined,
        totalResidual,
        maxResidual,
        equivalentUniformLeafCount,
        adaptivityRatio,
        timingMs: {
            initialLeaves: Math.round((tLeavesAlloced - t0) * 100) / 100,
            refine: Math.round((tRefined - tLeavesAlloced) * 100) / 100,
            total: Math.round((tRefined - t0) * 100) / 100,
        },
    }
    return result
}

/**
 * Auto-tune the residual threshold so a target percentile of cubes are flagged for
 * subdivision. Useful when the user doesn't have a feel for what residual values to
 * expect (they depend on `voxelSize` and SDF magnitude).
 *
 * `targetRefinedFraction` of 0.05 = "flag the top 5% most-curved cubes for subdivision".
 */
export function pickResidualThresholdFromPercentile(
    residuals: Float32Array,
    targetRefinedFraction: number,
): number {
    const safeFraction = Math.max(0, Math.min(1, targetRefinedFraction))
    if (residuals.length === 0 || safeFraction === 0) return Infinity

    // Copy + sort ascending. For very large arrays this is O(N log N); CPU-side stage 1
    // is fine, will move to a GPU radix-sort if it ever becomes a bottleneck.
    const sorted = new Float32Array(residuals)
    sorted.sort()
    const idx = Math.floor((1 - safeFraction) * sorted.length)
    return sorted[Math.min(idx, sorted.length - 1)] ?? Infinity
}

/**
 * Format the octree build result as a single human-readable line for `dbgLog` output.
 * Includes leaf totals, per-depth distribution, residual range, and adaptivity ratio.
 */
export function formatOctreeStats(result: OctreeBuildResult): string {
    const perDepth = Array.from(result.leavesPerDepth.entries())
        .sort((a, b) => a[0] - b[0])
        .map(([d, n]) => `d${d}=${n}`)
        .join(",")
    const ratioPct = (result.adaptivityRatio * 100).toFixed(2)
    const t = result.timingMs
    return `octree: leaves=${result.leaves.length} (${perDepth}), refined=${result.baseCubesRefined} base cubes, `
        + `residual sum=${result.totalResidual.toExponential(3)} max=${result.maxResidual.toExponential(3)}, `
        + `adaptivity=${ratioPct}% of uniform@maxDepth, CPU ${t.total} ms`
}

/** Convenience: log the octree statistics under the IsoExport debug module. */
export function logOctreeStats(result: OctreeBuildResult): void {
    dbgLog("IsoExport").debug(formatOctreeStats(result))
}

// ============================== Stage 4 Sessions 2, 5, 6 ==============================
// GPU sub-cube / sub-edge / sub-face dual placement support — all keyed by GLOBAL
// sub-grid coordinates rather than parent-relative encoding.
//
// Why global coords: at refined-parent boundaries, a single sub-edge or sub-face can
// touch up to 4 (sub-edge) or 2 (sub-face) refined parents. Per-parent emission would
// produce up to 4× duplicates that the depth-aware sparse hash (Session 6) can't
// disambiguate. Encoding each sub-cell by its global sub-grid linear index makes
// canonical-owner dedup trivial — a single `Set<linearIdx>` collapses all duplicates,
// and the resulting descriptor list maps 1:1 onto unique hash entries.
//
// Session 2 (current) only supports depth-1 leaves. Depth-2+ leaves get counted as
// `skippedDeeperLeaves` for diagnostics; future work will widen the descriptor + add a
// recursive Pass for deeper sub-cells.
//
// Sub-grid dimensions: with depth-1 refinement, sub-voxel = base voxel × ½. The sub-grid
// has 2× as many cells per axis as the base grid:
//   sub-cell counts:    sub_nx = 2*nx, sub_ny = 2*ny, sub_nz = 2*nz
//   sub-corner counts:  sub_nx + 1 = 2*nx + 1, etc.
// Linear index formulas mirror the base-grid `face_idx_xy` / `cube_edge_grid_index`
// helpers in `iso.wgsl` but at sub-resolution.

/** A child sub-cube descriptor matching WGSL `childCubeInfo[i]` (vec4u) layout.
 *  Coordinates are GLOBAL sub-grid positions (range [0, 2*nx) × [0, 2*ny) × [0, 2*nz)).
 *  The depth-1 octree leaves directly encode sub-cube positions at this resolution. */
export interface ChildCubeInfo {
    gsx: number
    gsy: number
    gsz: number
}

/** A child sub-edge descriptor matching WGSL `childEdgeInfo[i]` (vec4u) layout.
 *  Coordinates are GLOBAL sub-grid lo-corner positions; range depends on axis:
 *    X-edge: gsx ∈ [0, 2*nx),     gsy ∈ [0, 2*ny+1), gsz ∈ [0, 2*nz+1)
 *    Y-edge: gsx ∈ [0, 2*nx+1), gsy ∈ [0, 2*ny),     gsz ∈ [0, 2*nz+1)
 *    Z-edge: gsx ∈ [0, 2*nx+1), gsy ∈ [0, 2*ny+1), gsz ∈ [0, 2*nz)
 *  axis: 0 = X-edge, 1 = Y-edge, 2 = Z-edge. */
export interface ChildEdgeInfo {
    gsx: number
    gsy: number
    gsz: number
    axis: 0 | 1 | 2
}

/** A child sub-face descriptor matching WGSL `childFaceInfo[i]` (vec4u) layout.
 *  Coordinates are GLOBAL sub-grid min-corner positions; range depends on axis (the
 *  axis perpendicular to the face):
 *    YZ-face (axis=0): gsx ∈ [0, 2*nx+1), gsy ∈ [0, 2*ny),   gsz ∈ [0, 2*nz)
 *    XZ-face (axis=1): gsx ∈ [0, 2*nx),   gsy ∈ [0, 2*ny+1), gsz ∈ [0, 2*nz)
 *    XY-face (axis=2): gsx ∈ [0, 2*nx),   gsy ∈ [0, 2*ny),   gsz ∈ [0, 2*nz+1)
 *  axis: 0 = YZ-face (perp X), 1 = XZ-face (perp Y), 2 = XY-face (perp Z). */
export interface ChildFaceInfo {
    gsx: number
    gsy: number
    gsz: number
    axis: 0 | 1 | 2
}

// ---------- Linear-index formulas (CPU) for the sparse hash extension ----------
// Each sub-cell category maps a global sub-grid coord to a unique linear index. Must
// match `subCellLinearIdx*` helpers in `iso.wgsl` exactly (Session 6 work).

/** Linear index for a sub-cube at global sub-grid coords. Range: [0, 2*nx × 2*ny × 2*nz). */
export function subCubeLinearIdx(gsx: number, gsy: number, gsz: number, nxBase: number, nyBase: number): number {
    return gsx + gsy * (2 * nxBase) + gsz * (2 * nxBase) * (2 * nyBase)
}

/** Linear index for an X-sub-edge. Range: [0, 2*nx × (2*ny+1) × (2*nz+1)). */
export function subEdgeXLinearIdx(gsx: number, gsy: number, gsz: number, nxBase: number, nyBase: number): number {
    return gsx + gsy * (2 * nxBase) + gsz * (2 * nxBase) * (2 * nyBase + 1)
}

/** Linear index for a Y-sub-edge. Range: [0, (2*nx+1) × 2*ny × (2*nz+1)). */
export function subEdgeYLinearIdx(gsx: number, gsy: number, gsz: number, nxBase: number, nyBase: number): number {
    return gsx + gsy * (2 * nxBase + 1) + gsz * (2 * nxBase + 1) * (2 * nyBase)
}

/** Linear index for a Z-sub-edge. Range: [0, (2*nx+1) × (2*ny+1) × 2*nz). */
export function subEdgeZLinearIdx(gsx: number, gsy: number, gsz: number, nxBase: number, nyBase: number): number {
    return gsx + gsy * (2 * nxBase + 1) + gsz * (2 * nxBase + 1) * (2 * nyBase + 1)
}

/** Linear index for a YZ-sub-face (perpendicular to X). Range: [0, (2*nx+1) × 2*ny × 2*nz). */
export function subFaceYZLinearIdx(gsx: number, gsy: number, gsz: number, nxBase: number, nyBase: number): number {
    return gsx + gsy * (2 * nxBase + 1) + gsz * (2 * nxBase + 1) * (2 * nyBase)
}

/** Linear index for an XZ-sub-face (perpendicular to Y). Range: [0, 2*nx × (2*ny+1) × 2*nz). */
export function subFaceXZLinearIdx(gsx: number, gsy: number, gsz: number, nxBase: number, nyBase: number): number {
    return gsx + gsy * (2 * nxBase) + gsz * (2 * nxBase) * (2 * nyBase + 1)
}

/** Linear index for an XY-sub-face (perpendicular to Z). Range: [0, 2*nx × 2*ny × (2*nz+1)). */
export function subFaceXYLinearIdx(gsx: number, gsy: number, gsz: number, nxBase: number, nyBase: number): number {
    return gsx + gsy * (2 * nxBase) + gsz * (2 * nxBase) * (2 * nyBase)
}

/**
 * Walk the octree leaves and emit one `ChildCubeInfo` per UNIQUE depth-1 leaf
 * (already deduplicated — sub-cubes are interior to a parent and never shared
 * between refined parents, so each depth-1 leaf is naturally unique).
 *
 * Returns the child list AND the count of skipped deeper-than-1 leaves so the
 * orchestrator can log "N depth-2+ leaves not yet supported by Pass 11".
 */
export function buildChildCubeListFromOctree(octree: OctreeBuildResult): {
    children: ChildCubeInfo[]
    skippedDeeperLeaves: number
} {
    const children: ChildCubeInfo[] = []
    let skippedDeeperLeaves = 0

    for (const leaf of octree.leaves) {
        if (leaf.depth === 0) continue
        if (leaf.depth > 1) {
            skippedDeeperLeaves++
            continue
        }
        // Depth-1 leaf: leaf.cellPos is already at sub-grid (half-voxel) coords.
        children.push({ gsx: leaf.cellPos[0], gsy: leaf.cellPos[1], gsz: leaf.cellPos[2] })
    }

    return { children, skippedDeeperLeaves }
}

/** Stride in u32 of one packed `ChildCubeInfo` entry — must match `vec4u` layout. */
export const CHILD_CUBE_INFO_STRIDE_U32 = 4

/** Pack the child-cube list into a Uint32Array for GPU upload.
 *  Layout: vec4u(gsx, gsy, gsz, _padding). */
export function packChildCubeInfo(children: ChildCubeInfo[]): Uint32Array {
    const packed = new Uint32Array(children.length * CHILD_CUBE_INFO_STRIDE_U32)
    for (let i = 0; i < children.length; i++) {
        const c = children[i]!
        packed[i * CHILD_CUBE_INFO_STRIDE_U32] = c.gsx >>> 0
        packed[i * CHILD_CUBE_INFO_STRIDE_U32 + 1] = c.gsy >>> 0
        packed[i * CHILD_CUBE_INFO_STRIDE_U32 + 2] = c.gsz >>> 0
        packed[i * CHILD_CUBE_INFO_STRIDE_U32 + 3] = 0
    }
    return packed
}

/**
 * Walk the octree's depth-1 leaves → unique refined parents → enumerate the parent's
 * 54 sub-edges (18 per axis) at GLOBAL sub-grid coordinates. Deduplicate sub-edges
 * shared between adjacent refined parents via a `Set<linearIdx>` per axis (a sub-edge
 * on a parent's boundary edge is touched by up to 4 refined parents; each emits the
 * same global linear index, the Set keeps one).
 *
 * Returns the dedupe'd ChildEdgeInfo[] AND skipped-deeper-leaf count.
 */
export function buildChildEdgeListFromOctree(
    octree: OctreeBuildResult,
    nxBase: number,
    nyBase: number,
): {
    edges: ChildEdgeInfo[]
    skippedDeeperLeaves: number
} {
    const edges: ChildEdgeInfo[] = []
    let skippedDeeperLeaves = 0
    const seenParents = new Set<number>()
    const seenX = new Set<number>()
    const seenY = new Set<number>()
    const seenZ = new Set<number>()
    const refinedParents: Array<[number, number, number]> = []
    for (const leaf of octree.leaves) {
        if (leaf.depth === 0) continue
        if (leaf.depth > 1) {
            skippedDeeperLeaves++
            continue
        }
        const px = leaf.cellPos[0] >> 1
        const py = leaf.cellPos[1] >> 1
        const pz = leaf.cellPos[2] >> 1
        // Pack to a single 32-bit dedup key. Components fit in 10 bits (assumes
        // base-grid coords ≤ 1024 per axis — well within typical CAD scales).
        const key = (px & 0x3ff) | ((py & 0x3ff) << 10) | ((pz & 0x3ff) << 20)
        if (seenParents.has(key)) continue
        seenParents.add(key)
        refinedParents.push([px, py, pz])
    }
    for (const [px, py, pz] of refinedParents) {
        const baseGsx = px * 2
        const baseGsy = py * 2
        const baseGsz = pz * 2
        // X-edges: lo-corner sx ∈ [0..1], sy ∈ [0..2], sz ∈ [0..2]
        for (let sx = 0; sx < 2; sx++) {
            for (let sy = 0; sy < 3; sy++) {
                for (let sz = 0; sz < 3; sz++) {
                    const gsx = baseGsx + sx
                    const gsy = baseGsy + sy
                    const gsz = baseGsz + sz
                    const lin = subEdgeXLinearIdx(gsx, gsy, gsz, nxBase, nyBase)
                    if (seenX.has(lin)) continue
                    seenX.add(lin)
                    edges.push({ gsx, gsy, gsz, axis: 0 })
                }
            }
        }
        // Y-edges: sx ∈ [0..2], sy ∈ [0..1], sz ∈ [0..2]
        for (let sx = 0; sx < 3; sx++) {
            for (let sy = 0; sy < 2; sy++) {
                for (let sz = 0; sz < 3; sz++) {
                    const gsx = baseGsx + sx
                    const gsy = baseGsy + sy
                    const gsz = baseGsz + sz
                    const lin = subEdgeYLinearIdx(gsx, gsy, gsz, nxBase, nyBase)
                    if (seenY.has(lin)) continue
                    seenY.add(lin)
                    edges.push({ gsx, gsy, gsz, axis: 1 })
                }
            }
        }
        // Z-edges: sx ∈ [0..2], sy ∈ [0..2], sz ∈ [0..1]
        for (let sx = 0; sx < 3; sx++) {
            for (let sy = 0; sy < 3; sy++) {
                for (let sz = 0; sz < 2; sz++) {
                    const gsx = baseGsx + sx
                    const gsy = baseGsy + sy
                    const gsz = baseGsz + sz
                    const lin = subEdgeZLinearIdx(gsx, gsy, gsz, nxBase, nyBase)
                    if (seenZ.has(lin)) continue
                    seenZ.add(lin)
                    edges.push({ gsx, gsy, gsz, axis: 2 })
                }
            }
        }
    }
    return { edges, skippedDeeperLeaves }
}

/**
 * Walk the octree's depth-1 leaves → unique refined parents → enumerate the parent's
 * 36 sub-faces at GLOBAL sub-grid coordinates. Deduplicate sub-faces shared between
 * the (up to 2) refined parents that share the corresponding parent face.
 */
export function buildChildFaceListFromOctree(
    octree: OctreeBuildResult,
    nxBase: number,
    nyBase: number,
): {
    faces: ChildFaceInfo[]
    skippedDeeperLeaves: number
} {
    const faces: ChildFaceInfo[] = []
    let skippedDeeperLeaves = 0
    const seenParents = new Set<number>()
    const seenYZ = new Set<number>()
    const seenXZ = new Set<number>()
    const seenXY = new Set<number>()
    const refinedParents: Array<[number, number, number]> = []
    for (const leaf of octree.leaves) {
        if (leaf.depth === 0) continue
        if (leaf.depth > 1) {
            skippedDeeperLeaves++
            continue
        }
        const px = leaf.cellPos[0] >> 1
        const py = leaf.cellPos[1] >> 1
        const pz = leaf.cellPos[2] >> 1
        const key = (px & 0x3ff) | ((py & 0x3ff) << 10) | ((pz & 0x3ff) << 20)
        if (seenParents.has(key)) continue
        seenParents.add(key)
        refinedParents.push([px, py, pz])
    }
    for (const [px, py, pz] of refinedParents) {
        const baseGsx = px * 2
        const baseGsy = py * 2
        const baseGsz = pz * 2
        // YZ-faces (perp X): sx ∈ [0..2], sy ∈ [0..1], sz ∈ [0..1]
        for (let sx = 0; sx < 3; sx++) {
            for (let sy = 0; sy < 2; sy++) {
                for (let sz = 0; sz < 2; sz++) {
                    const gsx = baseGsx + sx
                    const gsy = baseGsy + sy
                    const gsz = baseGsz + sz
                    const lin = subFaceYZLinearIdx(gsx, gsy, gsz, nxBase, nyBase)
                    if (seenYZ.has(lin)) continue
                    seenYZ.add(lin)
                    faces.push({ gsx, gsy, gsz, axis: 0 })
                }
            }
        }
        // XZ-faces (perp Y): sx ∈ [0..1], sy ∈ [0..2], sz ∈ [0..1]
        for (let sx = 0; sx < 2; sx++) {
            for (let sy = 0; sy < 3; sy++) {
                for (let sz = 0; sz < 2; sz++) {
                    const gsx = baseGsx + sx
                    const gsy = baseGsy + sy
                    const gsz = baseGsz + sz
                    const lin = subFaceXZLinearIdx(gsx, gsy, gsz, nxBase, nyBase)
                    if (seenXZ.has(lin)) continue
                    seenXZ.add(lin)
                    faces.push({ gsx, gsy, gsz, axis: 1 })
                }
            }
        }
        // XY-faces (perp Z): sx ∈ [0..1], sy ∈ [0..1], sz ∈ [0..2]
        for (let sx = 0; sx < 2; sx++) {
            for (let sy = 0; sy < 2; sy++) {
                for (let sz = 0; sz < 3; sz++) {
                    const gsx = baseGsx + sx
                    const gsy = baseGsy + sy
                    const gsz = baseGsz + sz
                    const lin = subFaceXYLinearIdx(gsx, gsy, gsz, nxBase, nyBase)
                    if (seenXY.has(lin)) continue
                    seenXY.add(lin)
                    faces.push({ gsx, gsy, gsz, axis: 2 })
                }
            }
        }
    }
    return { faces, skippedDeeperLeaves }
}

/** Pack a `ChildEdgeInfo[]` for GPU upload. Layout: vec4u(gsx, gsy, gsz, axis). */
export function packChildEdgeInfo(edges: ChildEdgeInfo[]): Uint32Array {
    const packed = new Uint32Array(edges.length * 4)
    for (let i = 0; i < edges.length; i++) {
        const e = edges[i]!
        packed[i * 4] = e.gsx >>> 0
        packed[i * 4 + 1] = e.gsy >>> 0
        packed[i * 4 + 2] = e.gsz >>> 0
        packed[i * 4 + 3] = e.axis & 3
    }
    return packed
}

/** Pack a `ChildFaceInfo[]` for GPU upload. Layout: vec4u(gsx, gsy, gsz, axis). */
export function packChildFaceInfo(faces: ChildFaceInfo[]): Uint32Array {
    const packed = new Uint32Array(faces.length * 4)
    for (let i = 0; i < faces.length; i++) {
        const f = faces[i]!
        packed[i * 4] = f.gsx >>> 0
        packed[i * 4 + 1] = f.gsy >>> 0
        packed[i * 4 + 2] = f.gsz >>> 0
        packed[i * 4 + 3] = f.axis & 3
    }
    return packed
}

// ============================== Stage 4 Session 6: sub-cell sparse hash builder ==============================

/** Cell-type IDs for sub-cells in the depth-aware sparse hash key. Must match the
 *  WGSL `CELL_TYPE_SUB_*` constants in `iso.wgsl`. Base cell types (0..7) are
 *  re-exported from `iso-sparse.mts`. */
export const CELL_TYPE_SUB_CUBE = 8
export const CELL_TYPE_SUB_EDGE_X = 9
export const CELL_TYPE_SUB_EDGE_Y = 10
export const CELL_TYPE_SUB_EDGE_Z = 11
export const CELL_TYPE_SUB_FACE_YZ = 12
export const CELL_TYPE_SUB_FACE_XZ = 13
export const CELL_TYPE_SUB_FACE_XY = 14

/** Sub-cell sparse hash table built from the deduped sub-cell descriptor lists.
 *  Each entry maps `(subCellType, sub_grid_linearIdx)` → ABSOLUTE slot index in the
 *  unified `subCellAllDuals` buffer (Stage 4 Session 7). The `subCubeBase`,
 *  `subEdgeBase`, `subFaceBase` fields tell the orchestrator the per-pass write
 *  offsets to upload to `uniforms.subCellBases`. */
export interface SubCellSparseHash {
    /** Open-addressed (key, slot) pairs; matches WGSL `subDualHashTable` layout. */
    hashTable: Uint32Array
    /** Power-of-two entry count = `hashTable.length / 2`. */
    hashEntries: number
    /** `hashEntries - 1`; passed to WGSL as `uniforms.subSparseHash.x`. */
    hashMask: number
    /** Total slots inserted = subCubeCount + subEdgeCount + subFaceCount. */
    totalSlots: number
    /** Absolute write base for sub-cubes in `subCellAllDuals` (always 0). */
    subCubeBase: number
    /** Absolute write base for sub-edges = subCubeCount. */
    subEdgeBase: number
    /** Absolute write base for sub-faces = subCubeCount + subEdgeCount. */
    subFaceBase: number
}

const SUB_HASH_KNUTH = 0x9e3779b1 | 0  // matches SPARSE_HASH_KNUTH in iso-sparse.mts
const SUB_HASH_KEY_EMPTY = 0xffffffff

function makeSubKey(cellType: number, linearIdx: number): number {
    // Mirror WGSL `make_sparse_key`: cellType in upper 4 bits, linearIdx in lower 28.
    return ((cellType & 0xf) << 28) | (linearIdx & 0x0fffffff)
}

/**
 * Build the sub-cell sparse hash table from the deduplicated descriptor lists.
 *
 * Stage 4 Session 7: slot is now an ABSOLUTE index into the unified
 * `subCellAllDuals` GPU buffer. Layout:
 *   slots [0,                          numSubCubes)  — sub-cubes
 *   slots [numSubCubes,                numSubCubes + numSubEdges)  — sub-edges
 *   slots [numSubCubes + numSubEdges,  total)  — sub-faces
 *
 * Pass 11/12/13 write to `subCellAllDuals[base + dispatch_index]` where bases are
 * supplied via `uniforms.subCellBases`. The hash builder mirrors that base addressing.
 *
 * Hash capacity: `next_power_of_two(2 × totalSlots)` — 50% load factor.
 */
export function buildSubCellSparseHash(
    subCubes: ChildCubeInfo[],
    subEdges: ChildEdgeInfo[],
    subFaces: ChildFaceInfo[],
    nxBase: number,
    nyBase: number,
): SubCellSparseHash {
    const totalSlots = subCubes.length + subEdges.length + subFaces.length
    const subCubeBase = 0
    const subEdgeBase = subCubes.length
    const subFaceBase = subCubes.length + subEdges.length

    // Empty case: return a 1-entry-marked-empty hash so the WGSL `mask == 0u` early-out
    // path takes effect cleanly.
    if (totalSlots === 0) {
        const hashTable = new Uint32Array(2)
        hashTable[0] = SUB_HASH_KEY_EMPTY
        hashTable[1] = SUB_HASH_KEY_EMPTY
        return {
            hashTable, hashEntries: 1, hashMask: 0, totalSlots: 0,
            subCubeBase, subEdgeBase, subFaceBase,
        }
    }

    let hashEntries = 1
    const target = Math.max(64, totalSlots * 4)
    while (hashEntries < target) hashEntries <<= 1
    const hashMask = hashEntries - 1
    const hashTable = new Uint32Array(hashEntries * 2)
    hashTable.fill(SUB_HASH_KEY_EMPTY)

    const insertHash = (key: number, slot: number) => {
        let probe = (Math.imul(key >>> 0, SUB_HASH_KNUTH) >>> 0) & hashMask
        for (let i = 0; i < 4096; i++) {
            const base2 = probe * 2
            if (hashTable[base2] === SUB_HASH_KEY_EMPTY) {
                hashTable[base2] = key >>> 0
                hashTable[base2 + 1] = slot >>> 0
                return
            }
            probe = (probe + 1) & hashMask
        }
        throw new Error(
            `Sub-cell sparse hash insert overflowed 4096 probes at key=${key}, slot=${slot}; `
            + `entries=${hashEntries}, totalSlots=${totalSlots}`,
        )
    }

    // Sub-cubes: slot = subCubeBase + index in subCubes[].
    for (let i = 0; i < subCubes.length; i++) {
        const c = subCubes[i]!
        const linear = subCubeLinearIdx(c.gsx, c.gsy, c.gsz, nxBase, nyBase)
        insertHash(makeSubKey(CELL_TYPE_SUB_CUBE, linear), subCubeBase + i)
    }
    for (let i = 0; i < subEdges.length; i++) {
        const e = subEdges[i]!
        let key: number
        if (e.axis === 0) {
            key = makeSubKey(CELL_TYPE_SUB_EDGE_X, subEdgeXLinearIdx(e.gsx, e.gsy, e.gsz, nxBase, nyBase))
        } else if (e.axis === 1) {
            key = makeSubKey(CELL_TYPE_SUB_EDGE_Y, subEdgeYLinearIdx(e.gsx, e.gsy, e.gsz, nxBase, nyBase))
        } else {
            key = makeSubKey(CELL_TYPE_SUB_EDGE_Z, subEdgeZLinearIdx(e.gsx, e.gsy, e.gsz, nxBase, nyBase))
        }
        insertHash(key, subEdgeBase + i)
    }
    for (let i = 0; i < subFaces.length; i++) {
        const f = subFaces[i]!
        let key: number
        if (f.axis === 0) {
            key = makeSubKey(CELL_TYPE_SUB_FACE_YZ, subFaceYZLinearIdx(f.gsx, f.gsy, f.gsz, nxBase, nyBase))
        } else if (f.axis === 1) {
            key = makeSubKey(CELL_TYPE_SUB_FACE_XZ, subFaceXZLinearIdx(f.gsx, f.gsy, f.gsz, nxBase, nyBase))
        } else {
            key = makeSubKey(CELL_TYPE_SUB_FACE_XY, subFaceXYLinearIdx(f.gsx, f.gsy, f.gsz, nxBase, nyBase))
        }
        insertHash(key, subFaceBase + i)
    }

    return { hashTable, hashEntries, hashMask, totalSlots, subCubeBase, subEdgeBase, subFaceBase }
}

/**
 * Compute summary statistics about an array of QEF residuals (parent or child).
 * Useful for "did refinement help?" comparisons in the diagnostic log: if the
 * child residual distribution is significantly LOWER than the parent residuals
 * for the same cubes, the refinement is mathematically working — each sub-cube
 * fits the local SDF tangent planes better than the parent did.
 */
export function summarizeResidualDistribution(residuals: Float32Array | number[]): {
    count: number
    sum: number
    max: number
    mean: number
    /** P50 of finite, non-negative residuals. */
    median: number
    /** P95 of finite, non-negative residuals. */
    p95: number
} {
    let count = 0
    let sum = 0
    let max = 0
    const sorted: number[] = []
    for (let i = 0; i < residuals.length; i++) {
        const v = residuals[i]!
        if (!Number.isFinite(v) || v < 0) continue
        count++
        sum += v
        if (v > max) max = v
        sorted.push(v)
    }
    sorted.sort((a, b) => a - b)
    const median = count > 0 ? (sorted[Math.floor(count * 0.5)] ?? 0) : 0
    const p95 = count > 0 ? (sorted[Math.floor(count * 0.95)] ?? 0) : 0
    const mean = count > 0 ? sum / count : 0
    return { count, sum, max, mean, median, p95 }
}

// ============================== Phase 5 (Session 9): minimal-cube enumeration ==============================
//
// `buildMinimalCubeList` enumerates the cubes that Pass 15 (multi-resolution MT) must walk:
//
//   1. Every depth-1 sub-cube of every refined parent (8 per parent). These are the
//      sub-cubes themselves; they're "minimal" because their parent is no longer minimal.
//   2. Every active depth-0 base cube that has a refined cube as a face- or edge-neighbour
//      (= within Manhattan distance √2). These cubes themselves are still depth-0 minimal,
//      but at least one of their 12 base edges has a refined cube around it, so Pass 6
//      skips that edge in adaptive mode and Pass 15 must emit those tets.
//
// Pass 6 and Pass 15 form a partition of mesh emission: an active base cube C is processed
// either by Pass 6 (when no neighbour is refined within edge-share distance) or by Pass 15
// (when at least one is). The two never both emit for the same minimal cube.
//
// Coordinate convention: every minimal cube descriptor stores SUB-grid coords:
//   - Depth-0 (unrefined): gsx = 2*cx, gsy = 2*cy, gsz = 2*cz. The cube spans sub-grid
//     positions [2*cx, 2*cx+2). This matches the depth-1 convention so the WGSL walk
//     code is uniform.
//   - Depth-1 (sub-cube): gsx = sub-cube's actual sub-grid x. Cube spans [gsx, gsx+1).
//
// Per-descriptor packed layout (16 bytes = 1 vec4u, suitable for packing into the tail of
// `subCellAllDuals` alongside other Stage-4 sub-cell data):
//   word 0: gsx
//   word 1: gsy
//   word 2: gsz
//   word 3: bit 0       = depth (0 or 1)
//           bits 1..6   = neighbourRefinedMask (only meaningful for depth=0)
//                         bit  0 = -X, 1 = +X, 2 = -Y, 3 = +Y, 4 = -Z, 5 = +Z
//                         (after the depth bit, so positions 1..6 in the u32)
//           bits 7..    = reserved
//
// The neighbourRefinedMask only covers FACE neighbours (6 directions). Edge-neighbour
// refinement (12 directions) is queried per-base-edge by the WGSL shader using its own
// `is_base_cube_refined` helper; tracking it CPU-side would 4x the descriptor size for
// no gain.

export interface MinimalCubeListResult {
    /** Packed `vec4u` per minimal cube. Length = numMinimalCubes × 4. */
    descriptors: Uint32Array
    /** Number of minimal-cube descriptors (= descriptors.length / 4). */
    numMinimalCubes: number
    /** How many depth-0 unrefined-but-pass15-territory cubes are in `descriptors`. */
    numDepth0: number
    /** How many depth-1 sub-cubes are in `descriptors`. */
    numDepth1: number
}

/**
 * Build the minimal-cube list for Pass 15 dispatch.
 *
 * `octreeChildren` is the depth-1 sub-cube list produced by `buildChildCubeListFromOctree`
 * (each entry has gsx/gsy/gsz at sub-grid resolution). We deliberately accept this rather
 * than the raw octree so the adaptive orchestrator can reuse the existing build.
 *
 * `activeCubeCompactList` is `sparse.cubeCompactList` (linear base-cube indices that have
 * a sign change among their 8 corners — the cubes Pass 6 would normally process).
 */
export function buildMinimalCubeList(
    octreeChildren: ChildCubeInfo[],
    activeCubeCompactList: Uint32Array,
    nxBase: number,
    nyBase: number,
    nzBase: number,
): MinimalCubeListResult {
    // Step 1: build a refined-base-cube bitset from the children list (each child sub-cube
    // implies its parent is refined). Dedup via Set since 8 children per parent map to 1
    // bit in the bitset.
    const refinedParentBits = new Uint32Array(Math.max(1, Math.ceil(nxBase * nyBase * nzBase / 32)))
    const refinedParentSet = new Set<number>()
    for (const c of octreeChildren) {
        const px = c.gsx >> 1
        const py = c.gsy >> 1
        const pz = c.gsz >> 1
        const linear = px + py * nxBase + pz * nxBase * nyBase
        if (refinedParentSet.has(linear)) continue
        refinedParentSet.add(linear)
        refinedParentBits[Math.floor(linear / 32)]! |= 1 << (linear % 32)
    }

    const isRefined = (cx: number, cy: number, cz: number): boolean => {
        if (cx < 0 || cx >= nxBase || cy < 0 || cy >= nyBase || cz < 0 || cz >= nzBase) return false
        const linear = cx + cy * nxBase + cz * nxBase * nyBase
        return (refinedParentBits[Math.floor(linear / 32)]! & (1 << (linear % 32))) !== 0
    }

    // Step 2: build a bitset of "Pass 15 territory" depth-0 cubes — the unrefined base
    // cubes that have at least one of their 12 base edges with a refined neighbour. We
    // dilate the refined set by the 18 face/edge-neighbour offsets (NOT the 8 corner-only
    // offsets — corner-neighbours don't share any base edge with C, so their refinement
    // doesn't force C into Pass 15 territory).
    const pass15TerritoryBits = new Uint32Array(refinedParentBits.length)
    const dilateOffsets: Array<[number, number, number]> = []
    for (let dx = -1; dx <= 1; dx++) {
        for (let dy = -1; dy <= 1; dy++) {
            for (let dz = -1; dz <= 1; dz++) {
                if (dx === 0 && dy === 0 && dz === 0) continue
                const absSum = Math.abs(dx) + Math.abs(dy) + Math.abs(dz)
                // Skip pure-corner offsets (|dx|+|dy|+|dz| == 3) — those neighbours share
                // only a corner with the centre cube and don't constrain Pass 15 territory.
                if (absSum >= 3) continue
                dilateOffsets.push([dx, dy, dz])
            }
        }
    }
    // dilateOffsets has 6 face + 12 edge = 18 entries.
    for (const linear of refinedParentSet) {
        const cz = Math.floor(linear / (nxBase * nyBase))
        const cy = Math.floor((linear - cz * nxBase * nyBase) / nxBase)
        const cx = linear - cy * nxBase - cz * nxBase * nyBase
        for (const [dx, dy, dz] of dilateOffsets) {
            const nx = cx + dx, ny = cy + dy, nz = cz + dz
            if (nx < 0 || nx >= nxBase || ny < 0 || ny >= nyBase || nz < 0 || nz >= nzBase) continue
            const nLinear = nx + ny * nxBase + nz * nxBase * nyBase
            // Skip if neighbour itself is refined — those are handled as depth-1 sub-cubes.
            if (refinedParentSet.has(nLinear)) continue
            pass15TerritoryBits[Math.floor(nLinear / 32)]! |= 1 << (nLinear % 32)
        }
    }

    // Step 3: walk active base cubes (sparse.cubeCompactList) and emit minimal-cube
    // descriptors for the ones that need Pass 15:
    //   - Refined → 8 sub-cube descriptors at depth 1
    //   - Unrefined AND in pass15Territory → 1 descriptor at depth 0 with face mask
    //   - Otherwise → not emitted (Pass 6 handles fine)
    const out: number[] = []
    let numDepth0 = 0, numDepth1 = 0
    for (let i = 0; i < activeCubeCompactList.length; i++) {
        const linear = activeCubeCompactList[i]!
        const cx = linear % nxBase
        const cy = Math.floor(linear / nxBase) % nyBase
        const cz = Math.floor(linear / (nxBase * nyBase))
        if (refinedParentSet.has(linear)) {
            // Emit 8 sub-cubes at depth 1.
            for (let oct = 0; oct < 8; oct++) {
                const sx = cx * 2 + (oct & 1)
                const sy = cy * 2 + ((oct >> 1) & 1)
                const sz = cz * 2 + ((oct >> 2) & 1)
                out.push(sx, sy, sz, 1) // word 3: depth=1, mask irrelevant
                numDepth1++
            }
            continue
        }
        const wordIdx = Math.floor(linear / 32)
        const bitIdx = linear % 32
        if ((pass15TerritoryBits[wordIdx]! & (1 << bitIdx)) === 0) continue

        // Unrefined depth-0 cube in Pass 15 territory. Compute face-neighbour mask.
        let mask = 0
        if (isRefined(cx - 1, cy, cz)) mask |= 1 << 0  // -X
        if (isRefined(cx + 1, cy, cz)) mask |= 1 << 1  // +X
        if (isRefined(cx, cy - 1, cz)) mask |= 1 << 2  // -Y
        if (isRefined(cx, cy + 1, cz)) mask |= 1 << 3  // +Y
        if (isRefined(cx, cy, cz - 1)) mask |= 1 << 4  // -Z
        if (isRefined(cx, cy, cz + 1)) mask |= 1 << 5  // +Z
        // Pack: depth at bit 0, mask at bits 1..6.
        const word3 = 0 | (mask << 1)
        out.push(cx * 2, cy * 2, cz * 2, word3)
        numDepth0++
    }

    return {
        descriptors: new Uint32Array(out),
        numMinimalCubes: numDepth0 + numDepth1,
        numDepth0,
        numDepth1,
    }
}
