#!/usr/bin/env bash
set -euo pipefail

hash="$(git describe --always --dirty)"
tag="$(git tag -l --points-at "${hash%-dirty}")"
if [[ -n $tag ]]; then
    if [[ $hash == *"-dirty" ]]; then
        echo "$tag-dirty"
    else
        echo "$tag"
    fi
else
    echo "v0.0.0-$hash"
fi
