/**
 * Lazy, once-per-worker loader for the gcad-wasm SFCC kernel.
 *
 * The render worker is a module worker, so it can import the wasm-pack
 * `--target web` ESM glue directly. esbuild bundles the glue; the `.wasm` binary
 * is imported with esbuild's `file` loader (→ a URL the dev/prod server serves),
 * and we pass that URL explicitly to the generated `init` so the glue never falls
 * back to its `import.meta.url`-relative fetch.
 *
 * `pkg/` is a build artifact (gitignored), regenerated by
 * `cd gcad-wasm/wasm && wasm-pack build --target web`. If it is absent the import
 * fails at build time with a clear "module not found" — run wasm-pack first.
 */

// The generated ESM glue (default export = init) + the exported boundary fns.
import init, { export_sfcc, version } from "../../../gcad-wasm/wasm/pkg/gcad_wasm.js"
// esbuild `file` loader → a served URL string for the wasm binary.
import wasmUrl from "../../../gcad-wasm/wasm/pkg/gcad_wasm_bg.wasm"

let ready: Promise<void> | null = null

/** Initialize the wasm module exactly once (idempotent across calls). */
export async function ensureWasmReady(): Promise<void> {
    if (!ready) {
        ready = init(wasmUrl as unknown as string).then(() => undefined)
    }
    return ready
}

export { export_sfcc, version }
